package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Atblgraphs generated by hbm2java
 */
public class Atblgraphs implements java.io.Serializable {

	private AtblgraphsId id;

	public Atblgraphs() {
	}

	public Atblgraphs(AtblgraphsId id) {
		this.id = id;
	}

	public AtblgraphsId getId() {
		return this.id;
	}

	public void setId(AtblgraphsId id) {
		this.id = id;
	}

}
