package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * MessagesId generated by hbm2java
 */
public class MessagesId implements java.io.Serializable {

	private Integer codemsg;
	private int codelangue;
	private String msgLibelle;
	private String msgTheme;
	private int msgEmplacement;

	public MessagesId() {
	}

	public MessagesId(int codelangue, String msgLibelle, String msgTheme,
			int msgEmplacement) {
		this.codelangue = codelangue;
		this.msgLibelle = msgLibelle;
		this.msgTheme = msgTheme;
		this.msgEmplacement = msgEmplacement;
	}

	public MessagesId(Integer codemsg, int codelangue, String msgLibelle,
			String msgTheme, int msgEmplacement) {
		this.codemsg = codemsg;
		this.codelangue = codelangue;
		this.msgLibelle = msgLibelle;
		this.msgTheme = msgTheme;
		this.msgEmplacement = msgEmplacement;
	}

	public Integer getCodemsg() {
		return this.codemsg;
	}

	public void setCodemsg(Integer codemsg) {
		this.codemsg = codemsg;
	}

	public int getCodelangue() {
		return this.codelangue;
	}

	public void setCodelangue(int codelangue) {
		this.codelangue = codelangue;
	}

	public String getMsgLibelle() {
		return this.msgLibelle;
	}

	public void setMsgLibelle(String msgLibelle) {
		this.msgLibelle = msgLibelle;
	}

	public String getMsgTheme() {
		return this.msgTheme;
	}

	public void setMsgTheme(String msgTheme) {
		this.msgTheme = msgTheme;
	}

	public int getMsgEmplacement() {
		return this.msgEmplacement;
	}

	public void setMsgEmplacement(int msgEmplacement) {
		this.msgEmplacement = msgEmplacement;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MessagesId))
			return false;
		MessagesId castOther = (MessagesId) other;

		return ((this.getCodemsg() == castOther.getCodemsg()) || (this
				.getCodemsg() != null
				&& castOther.getCodemsg() != null && this.getCodemsg().equals(
				castOther.getCodemsg())))
				&& (this.getCodelangue() == castOther.getCodelangue())
				&& ((this.getMsgLibelle() == castOther.getMsgLibelle()) || (this
						.getMsgLibelle() != null
						&& castOther.getMsgLibelle() != null && this
						.getMsgLibelle().equals(castOther.getMsgLibelle())))
				&& ((this.getMsgTheme() == castOther.getMsgTheme()) || (this
						.getMsgTheme() != null
						&& castOther.getMsgTheme() != null && this
						.getMsgTheme().equals(castOther.getMsgTheme())))
				&& (this.getMsgEmplacement() == castOther.getMsgEmplacement());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodemsg() == null ? 0 : this.getCodemsg().hashCode());
		result = 37 * result + this.getCodelangue();
		result = 37
				* result
				+ (getMsgLibelle() == null ? 0 : this.getMsgLibelle()
						.hashCode());
		result = 37 * result
				+ (getMsgTheme() == null ? 0 : this.getMsgTheme().hashCode());
		result = 37 * result + this.getMsgEmplacement();
		return result;
	}

}
