package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Messages generated by hbm2java
 */
public class Messages implements java.io.Serializable {

	private MessagesId id;

	public Messages() {
	}

	public Messages(MessagesId id) {
		this.id = id;
	}

	public MessagesId getId() {
		return this.id;
	}

	public void setId(MessagesId id) {
		this.id = id;
	}

}
