package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OoActionLines generated by hbm2java
 */
public class OoActionLines implements java.io.Serializable {

	private Integer idx;
	private String descripcion;
	private String tipo;
	private String autor;
	private String aprobador;
	private String verificador;
	private String asignadoa;
	private String estado;
	private Integer parentId;
	private Integer actionId;
	private String anexoId;
	private String anexoDocId;
	private Boolean isEficaz;
	private Integer costeEstimado;
	private Integer costeReal;
	private Date fecha;
	private Date fechaPrevista;
	private Date fechaReal;
	private String observaciones;

	public OoActionLines() {
	}

	public OoActionLines(String descripcion, String tipo, String autor,
			String aprobador, String verificador, String asignadoa,
			String estado, Integer parentId, Integer actionId, String anexoId,
			String anexoDocId, Boolean isEficaz, Integer costeEstimado,
			Integer costeReal, Date fecha, Date fechaPrevista, Date fechaReal,
			String observaciones) {
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.autor = autor;
		this.aprobador = aprobador;
		this.verificador = verificador;
		this.asignadoa = asignadoa;
		this.estado = estado;
		this.parentId = parentId;
		this.actionId = actionId;
		this.anexoId = anexoId;
		this.anexoDocId = anexoDocId;
		this.isEficaz = isEficaz;
		this.costeEstimado = costeEstimado;
		this.costeReal = costeReal;
		this.fecha = fecha;
		this.fechaPrevista = fechaPrevista;
		this.fechaReal = fechaReal;
		this.observaciones = observaciones;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getAutor() {
		return this.autor;
	}

	public void setAutor(String autor) {
		this.autor = autor;
	}

	public String getAprobador() {
		return this.aprobador;
	}

	public void setAprobador(String aprobador) {
		this.aprobador = aprobador;
	}

	public String getVerificador() {
		return this.verificador;
	}

	public void setVerificador(String verificador) {
		this.verificador = verificador;
	}

	public String getAsignadoa() {
		return this.asignadoa;
	}

	public void setAsignadoa(String asignadoa) {
		this.asignadoa = asignadoa;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Integer getActionId() {
		return this.actionId;
	}

	public void setActionId(Integer actionId) {
		this.actionId = actionId;
	}

	public String getAnexoId() {
		return this.anexoId;
	}

	public void setAnexoId(String anexoId) {
		this.anexoId = anexoId;
	}

	public String getAnexoDocId() {
		return this.anexoDocId;
	}

	public void setAnexoDocId(String anexoDocId) {
		this.anexoDocId = anexoDocId;
	}

	public Boolean getIsEficaz() {
		return this.isEficaz;
	}

	public void setIsEficaz(Boolean isEficaz) {
		this.isEficaz = isEficaz;
	}

	public Integer getCosteEstimado() {
		return this.costeEstimado;
	}

	public void setCosteEstimado(Integer costeEstimado) {
		this.costeEstimado = costeEstimado;
	}

	public Integer getCosteReal() {
		return this.costeReal;
	}

	public void setCosteReal(Integer costeReal) {
		this.costeReal = costeReal;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getFechaPrevista() {
		return this.fechaPrevista;
	}

	public void setFechaPrevista(Date fechaPrevista) {
		this.fechaPrevista = fechaPrevista;
	}

	public Date getFechaReal() {
		return this.fechaReal;
	}

	public void setFechaReal(Date fechaReal) {
		this.fechaReal = fechaReal;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
