package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OoActions generated by hbm2java
 */
public class OoActions implements java.io.Serializable {

	private Integer idx;
	private Date fecha;
	private String tipo;
	private String descripcion;
	private String responsable;
	private Date fechaPrevista;
	private Date fechaCierre;
	private Boolean isEficaz;
	private String observaciones;
	private String graphAsociado;
	private String docAsociado;

	public OoActions() {
	}

	public OoActions(Date fecha, String tipo, String descripcion,
			String responsable, Date fechaPrevista, Date fechaCierre,
			Boolean isEficaz, String observaciones, String graphAsociado,
			String docAsociado) {
		this.fecha = fecha;
		this.tipo = tipo;
		this.descripcion = descripcion;
		this.responsable = responsable;
		this.fechaPrevista = fechaPrevista;
		this.fechaCierre = fechaCierre;
		this.isEficaz = isEficaz;
		this.observaciones = observaciones;
		this.graphAsociado = graphAsociado;
		this.docAsociado = docAsociado;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getResponsable() {
		return this.responsable;
	}

	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}

	public Date getFechaPrevista() {
		return this.fechaPrevista;
	}

	public void setFechaPrevista(Date fechaPrevista) {
		this.fechaPrevista = fechaPrevista;
	}

	public Date getFechaCierre() {
		return this.fechaCierre;
	}

	public void setFechaCierre(Date fechaCierre) {
		this.fechaCierre = fechaCierre;
	}

	public Boolean getIsEficaz() {
		return this.isEficaz;
	}

	public void setIsEficaz(Boolean isEficaz) {
		this.isEficaz = isEficaz;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getGraphAsociado() {
		return this.graphAsociado;
	}

	public void setGraphAsociado(String graphAsociado) {
		this.graphAsociado = graphAsociado;
	}

	public String getDocAsociado() {
		return this.docAsociado;
	}

	public void setDocAsociado(String docAsociado) {
		this.docAsociado = docAsociado;
	}

}
