package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoCells generated by hbm2java
 */
public class OoCells implements java.io.Serializable {

	private Integer idx;
	private String shGraphId;
	private String shFormId;
	private String shTypeId;
	private String shName;
	private String shNumber;
	private String shComment;
	private String shCenterX;
	private String shCenterY;
	private String shHeight;
	private String shWidth;
	private String shChildCount;
	private String shStyle;
	private String shParentId;
	private String shSourceId;

    private String shRelatedId;
    private String shRelatedName;

	public OoCells() {
	}

	public OoCells(String shGraphId, String shTypeId) {
		this.shGraphId = shGraphId;
		this.shTypeId = shTypeId;
	}

	public OoCells(String shGraphId, String shFormId, String shTypeId,
			String shName, String shNumber, String shComment, String shCenterX,
			String shCenterY, String shHeight, String shWidth,
			String shChildCount, String shStyle, String shParentId,
			String shSourceId,String shRelatedId,String shRelatedName) {
		this.shGraphId = shGraphId;
		this.shFormId = shFormId;
		this.shTypeId = shTypeId;
		this.shName = shName;
		this.shNumber = shNumber;
		this.shComment = shComment;
		this.shCenterX = shCenterX;
		this.shCenterY = shCenterY;
		this.shHeight = shHeight;
		this.shWidth = shWidth;
		this.shChildCount = shChildCount;
		this.shStyle = shStyle;
		this.shParentId = shParentId;
		this.shSourceId = shSourceId;
        this.shRelatedId = shRelatedId;
		this.shRelatedName = shRelatedName;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

    public String getShRelatedId()
    {
        return shRelatedId;
    }

    public void setShRelatedId(String shRelatedId)
    {
        this.shRelatedId = shRelatedId;
    }

    public String getShRelatedName()
    {
        return shRelatedName;
    }

    public void setShRelatedName(String shRelatedName)
    {
        this.shRelatedName = shRelatedName;
    }

	public String getShGraphId() {
		return this.shGraphId;
	}

	public void setShGraphId(String shGraphId) {
		this.shGraphId = shGraphId;
	}

	public String getShFormId() {
		return this.shFormId;
	}

	public void setShFormId(String shFormId) {
		this.shFormId = shFormId;
	}

	public String getShTypeId() {
		return this.shTypeId;
	}

	public void setShTypeId(String shTypeId) {
		this.shTypeId = shTypeId;
	}

	public String getShName() {
		return this.shName;
	}

	public void setShName(String shName) {
		this.shName = shName;
	}

	public String getShNumber() {
		return this.shNumber;
	}

	public void setShNumber(String shNumber) {
		this.shNumber = shNumber;
	}

	public String getShComment() {
		return this.shComment;
	}

	public void setShComment(String shComment) {
		this.shComment = shComment;
	}

	public String getShCenterX() {
		return this.shCenterX;
	}

	public void setShCenterX(String shCenterX) {
		this.shCenterX = shCenterX;
	}

	public String getShCenterY() {
		return this.shCenterY;
	}

	public void setShCenterY(String shCenterY) {
		this.shCenterY = shCenterY;
	}

	public String getShHeight() {
		return this.shHeight;
	}

	public void setShHeight(String shHeight) {
		this.shHeight = shHeight;
	}

	public String getShWidth() {
		return this.shWidth;
	}

	public void setShWidth(String shWidth) {
		this.shWidth = shWidth;
	}

	public String getShChildCount() {
		return this.shChildCount;
	}

	public void setShChildCount(String shChildCount) {
		this.shChildCount = shChildCount;
	}

	public String getShStyle() {
		return this.shStyle;
	}

	public void setShStyle(String shStyle) {
		this.shStyle = shStyle;
	}

	public String getShParentId() {
		return this.shParentId;
	}

	public void setShParentId(String shParentId) {
		this.shParentId = shParentId;
	}

	public String getShSourceId() {
		return this.shSourceId;
	}

	public void setShSourceId(String shSourceId) {
		this.shSourceId = shSourceId;
	}

}
