package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoDemands generated by hbm2java
 */
public class OoDemands implements java.io.Serializable {

	private OoDemandsId id;

	public OoDemands() {
	}

	public OoDemands(OoDemandsId id) {
		this.id = id;
	}

	public OoDemandsId getId() {
		return this.id;
	}

	public void setId(OoDemandsId id) {
		this.id = id;
	}

}
