package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OoDocFlow generated by hbm2java
 */
public class OoDocFlow implements java.io.Serializable {

	private Integer id;
	private int ord;
	private Integer type;
	private int codeUser;
	private String graphId;
	private String vote;
	private String message;
	private Date voteDate;

	public OoDocFlow() {
	}

	public OoDocFlow(int ord, int codeUser) {
		this.ord = ord;
		this.codeUser = codeUser;
	}

	public OoDocFlow(int ord, Integer type, int codeUser, String graphId,
			String vote, String message, Date voteDate) {
		this.ord = ord;
		this.type = type;
		this.codeUser = codeUser;
		this.graphId = graphId;
		this.vote = vote;
		this.message = message;
		this.voteDate = voteDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getOrd() {
		return this.ord;
	}

	public void setOrd(int ord) {
		this.ord = ord;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public int getCodeUser() {
		return this.codeUser;
	}

	public void setCodeUser(int codeUser) {
		this.codeUser = codeUser;
	}

	public String getGraphId() {
		return this.graphId;
	}

	public void setGraphId(String graphId) {
		this.graphId = graphId;
	}

	public String getVote() {
		return this.vote;
	}

	public void setVote(String vote) {
		this.vote = vote;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getVoteDate() {
		return this.voteDate;
	}

	public void setVoteDate(Date voteDate) {
		this.voteDate = voteDate;
	}

}
