package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoLogs generated by hbm2java
 */
public class OoLogs implements java.io.Serializable {

	private OoLogsId id;

	public OoLogs() {
	}

	public OoLogs(OoLogsId id) {
		this.id = id;
	}

	public OoLogsId getId() {
		return this.id;
	}

	public void setId(OoLogsId id) {
		this.id = id;
	}

}
