package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoOptions generated by hbm2java
 */
public class OoOptions implements java.io.Serializable {

	private Integer oid;
	private String baseDeDatos;
	private String connDriverClass;
	private String connString;
	private String connUser;
	private String connPassword;
	private String servidorOpenServer;
	private String carpetaGallery;
	private String carpetaModelosWord;
	private String carpetaRelaciones;
	private String carpetaTrabajo;
	private String carpetaTrabajoPublico;
	private String carpetaDifusionCreacion;
	private String carpetaDifusionAplicable;
	private String carpetaDifusionWeb;
	private String carpetaImportacion;
	private Boolean actualizarPropiedadesGrafico;
	private Boolean solicitarPropiedadesGrafico;
	private Boolean abrirGraficosAlInicio;
	private Boolean visualizarIndicadorCarpeta;
	private Boolean aplicarIntegridadReferencial;
	private Integer tiempoDeGuardado;
	private Boolean confirmarAntesDeGuardar;
	private Boolean documentoGuardarPorNombre;
	private Boolean webGuardarPorNombre;
	private Boolean proyectoGuardarPorNombre;
	private Boolean controlarCoherenciaSegunNivel;
	private Boolean desencadenarAlineacionRolesAutomatica;
	private Boolean utilizarFlechaDeAnguloRecto;
	private Boolean orientarPaginaEnFuncionDeAlineacion;
	private Boolean seleccionDeArchivoAlIndicarReferenciaDocumental;
	private Boolean visualizarSugerenciasInicio;
	private Boolean activarConsejos;
	private Boolean activarPanelDeInicio;
	private Boolean activarSeguridad;
	private Boolean activarSeguridadOo;
	private Boolean activarSeguridadSys;

	public OoOptions() {
	}

	public OoOptions(String baseDeDatos, String connDriverClass,
			String connString, String connUser, String connPassword,
			String servidorOpenServer, String carpetaGallery,
			String carpetaModelosWord, String carpetaRelaciones,
			String carpetaTrabajo, String carpetaTrabajoPublico,
			String carpetaDifusionCreacion, String carpetaDifusionAplicable,
			String carpetaDifusionWeb, String carpetaImportacion,
			Boolean actualizarPropiedadesGrafico,
			Boolean solicitarPropiedadesGrafico, Boolean abrirGraficosAlInicio,
			Boolean visualizarIndicadorCarpeta,
			Boolean aplicarIntegridadReferencial, Integer tiempoDeGuardado,
			Boolean confirmarAntesDeGuardar, Boolean documentoGuardarPorNombre,
			Boolean webGuardarPorNombre, Boolean proyectoGuardarPorNombre,
			Boolean controlarCoherenciaSegunNivel,
			Boolean desencadenarAlineacionRolesAutomatica,
			Boolean utilizarFlechaDeAnguloRecto,
			Boolean orientarPaginaEnFuncionDeAlineacion,
			Boolean seleccionDeArchivoAlIndicarReferenciaDocumental,
			Boolean visualizarSugerenciasInicio, Boolean activarConsejos,
			Boolean activarPanelDeInicio, Boolean activarSeguridad,
			Boolean activarSeguridadOo, Boolean activarSeguridadSys) {
		this.baseDeDatos = baseDeDatos;
		this.connDriverClass = connDriverClass;
		this.connString = connString;
		this.connUser = connUser;
		this.connPassword = connPassword;
		this.servidorOpenServer = servidorOpenServer;
		this.carpetaGallery = carpetaGallery;
		this.carpetaModelosWord = carpetaModelosWord;
		this.carpetaRelaciones = carpetaRelaciones;
		this.carpetaTrabajo = carpetaTrabajo;
		this.carpetaTrabajoPublico = carpetaTrabajoPublico;
		this.carpetaDifusionCreacion = carpetaDifusionCreacion;
		this.carpetaDifusionAplicable = carpetaDifusionAplicable;
		this.carpetaDifusionWeb = carpetaDifusionWeb;
		this.carpetaImportacion = carpetaImportacion;
		this.actualizarPropiedadesGrafico = actualizarPropiedadesGrafico;
		this.solicitarPropiedadesGrafico = solicitarPropiedadesGrafico;
		this.abrirGraficosAlInicio = abrirGraficosAlInicio;
		this.visualizarIndicadorCarpeta = visualizarIndicadorCarpeta;
		this.aplicarIntegridadReferencial = aplicarIntegridadReferencial;
		this.tiempoDeGuardado = tiempoDeGuardado;
		this.confirmarAntesDeGuardar = confirmarAntesDeGuardar;
		this.documentoGuardarPorNombre = documentoGuardarPorNombre;
		this.webGuardarPorNombre = webGuardarPorNombre;
		this.proyectoGuardarPorNombre = proyectoGuardarPorNombre;
		this.controlarCoherenciaSegunNivel = controlarCoherenciaSegunNivel;
		this.desencadenarAlineacionRolesAutomatica = desencadenarAlineacionRolesAutomatica;
		this.utilizarFlechaDeAnguloRecto = utilizarFlechaDeAnguloRecto;
		this.orientarPaginaEnFuncionDeAlineacion = orientarPaginaEnFuncionDeAlineacion;
		this.seleccionDeArchivoAlIndicarReferenciaDocumental = seleccionDeArchivoAlIndicarReferenciaDocumental;
		this.visualizarSugerenciasInicio = visualizarSugerenciasInicio;
		this.activarConsejos = activarConsejos;
		this.activarPanelDeInicio = activarPanelDeInicio;
		this.activarSeguridad = activarSeguridad;
		this.activarSeguridadOo = activarSeguridadOo;
		this.activarSeguridadSys = activarSeguridadSys;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public String getBaseDeDatos() {
		return this.baseDeDatos;
	}

	public void setBaseDeDatos(String baseDeDatos) {
		this.baseDeDatos = baseDeDatos;
	}

	public String getConnDriverClass() {
		return this.connDriverClass;
	}

	public void setConnDriverClass(String connDriverClass) {
		this.connDriverClass = connDriverClass;
	}

	public String getConnString() {
		return this.connString;
	}

	public void setConnString(String connString) {
		this.connString = connString;
	}

	public String getConnUser() {
		return this.connUser;
	}

	public void setConnUser(String connUser) {
		this.connUser = connUser;
	}

	public String getConnPassword() {
		return this.connPassword;
	}

	public void setConnPassword(String connPassword) {
		this.connPassword = connPassword;
	}

	public String getServidorOpenServer() {
		return this.servidorOpenServer;
	}

	public void setServidorOpenServer(String servidorOpenServer) {
		this.servidorOpenServer = servidorOpenServer;
	}

	public String getCarpetaGallery() {
		return this.carpetaGallery;
	}

	public void setCarpetaGallery(String carpetaGallery) {
		this.carpetaGallery = carpetaGallery;
	}

	public String getCarpetaModelosWord() {
		return this.carpetaModelosWord;
	}

	public void setCarpetaModelosWord(String carpetaModelosWord) {
		this.carpetaModelosWord = carpetaModelosWord;
	}

	public String getCarpetaRelaciones() {
		return this.carpetaRelaciones;
	}

	public void setCarpetaRelaciones(String carpetaRelaciones) {
		this.carpetaRelaciones = carpetaRelaciones;
	}

	public String getCarpetaTrabajo() {
		return this.carpetaTrabajo;
	}

	public void setCarpetaTrabajo(String carpetaTrabajo) {
		this.carpetaTrabajo = carpetaTrabajo;
	}

	public String getCarpetaTrabajoPublico() {
		return this.carpetaTrabajoPublico;
	}

	public void setCarpetaTrabajoPublico(String carpetaTrabajoPublico) {
		this.carpetaTrabajoPublico = carpetaTrabajoPublico;
	}

	public String getCarpetaDifusionCreacion() {
		return this.carpetaDifusionCreacion;
	}

	public void setCarpetaDifusionCreacion(String carpetaDifusionCreacion) {
		this.carpetaDifusionCreacion = carpetaDifusionCreacion;
	}

	public String getCarpetaDifusionAplicable() {
		return this.carpetaDifusionAplicable;
	}

	public void setCarpetaDifusionAplicable(String carpetaDifusionAplicable) {
		this.carpetaDifusionAplicable = carpetaDifusionAplicable;
	}

	public String getCarpetaDifusionWeb() {
		return this.carpetaDifusionWeb;
	}

	public void setCarpetaDifusionWeb(String carpetaDifusionWeb) {
		this.carpetaDifusionWeb = carpetaDifusionWeb;
	}

	public String getCarpetaImportacion() {
		return this.carpetaImportacion;
	}

	public void setCarpetaImportacion(String carpetaImportacion) {
		this.carpetaImportacion = carpetaImportacion;
	}

	public Boolean getActualizarPropiedadesGrafico() {
		return this.actualizarPropiedadesGrafico;
	}

	public void setActualizarPropiedadesGrafico(
			Boolean actualizarPropiedadesGrafico) {
		this.actualizarPropiedadesGrafico = actualizarPropiedadesGrafico;
	}

	public Boolean getSolicitarPropiedadesGrafico() {
		return this.solicitarPropiedadesGrafico;
	}

	public void setSolicitarPropiedadesGrafico(
			Boolean solicitarPropiedadesGrafico) {
		this.solicitarPropiedadesGrafico = solicitarPropiedadesGrafico;
	}

	public Boolean getAbrirGraficosAlInicio() {
		return this.abrirGraficosAlInicio;
	}

	public void setAbrirGraficosAlInicio(Boolean abrirGraficosAlInicio) {
		this.abrirGraficosAlInicio = abrirGraficosAlInicio;
	}

	public Boolean getVisualizarIndicadorCarpeta() {
		return this.visualizarIndicadorCarpeta;
	}

	public void setVisualizarIndicadorCarpeta(Boolean visualizarIndicadorCarpeta) {
		this.visualizarIndicadorCarpeta = visualizarIndicadorCarpeta;
	}

	public Boolean getAplicarIntegridadReferencial() {
		return this.aplicarIntegridadReferencial;
	}

	public void setAplicarIntegridadReferencial(
			Boolean aplicarIntegridadReferencial) {
		this.aplicarIntegridadReferencial = aplicarIntegridadReferencial;
	}

	public Integer getTiempoDeGuardado() {
		return this.tiempoDeGuardado;
	}

	public void setTiempoDeGuardado(Integer tiempoDeGuardado) {
		this.tiempoDeGuardado = tiempoDeGuardado;
	}

	public Boolean getConfirmarAntesDeGuardar() {
		return this.confirmarAntesDeGuardar;
	}

	public void setConfirmarAntesDeGuardar(Boolean confirmarAntesDeGuardar) {
		this.confirmarAntesDeGuardar = confirmarAntesDeGuardar;
	}

	public Boolean getDocumentoGuardarPorNombre() {
		return this.documentoGuardarPorNombre;
	}

	public void setDocumentoGuardarPorNombre(Boolean documentoGuardarPorNombre) {
		this.documentoGuardarPorNombre = documentoGuardarPorNombre;
	}

	public Boolean getWebGuardarPorNombre() {
		return this.webGuardarPorNombre;
	}

	public void setWebGuardarPorNombre(Boolean webGuardarPorNombre) {
		this.webGuardarPorNombre = webGuardarPorNombre;
	}

	public Boolean getProyectoGuardarPorNombre() {
		return this.proyectoGuardarPorNombre;
	}

	public void setProyectoGuardarPorNombre(Boolean proyectoGuardarPorNombre) {
		this.proyectoGuardarPorNombre = proyectoGuardarPorNombre;
	}

	public Boolean getControlarCoherenciaSegunNivel() {
		return this.controlarCoherenciaSegunNivel;
	}

	public void setControlarCoherenciaSegunNivel(
			Boolean controlarCoherenciaSegunNivel) {
		this.controlarCoherenciaSegunNivel = controlarCoherenciaSegunNivel;
	}

	public Boolean getDesencadenarAlineacionRolesAutomatica() {
		return this.desencadenarAlineacionRolesAutomatica;
	}

	public void setDesencadenarAlineacionRolesAutomatica(
			Boolean desencadenarAlineacionRolesAutomatica) {
		this.desencadenarAlineacionRolesAutomatica = desencadenarAlineacionRolesAutomatica;
	}

	public Boolean getUtilizarFlechaDeAnguloRecto() {
		return this.utilizarFlechaDeAnguloRecto;
	}

	public void setUtilizarFlechaDeAnguloRecto(
			Boolean utilizarFlechaDeAnguloRecto) {
		this.utilizarFlechaDeAnguloRecto = utilizarFlechaDeAnguloRecto;
	}

	public Boolean getOrientarPaginaEnFuncionDeAlineacion() {
		return this.orientarPaginaEnFuncionDeAlineacion;
	}

	public void setOrientarPaginaEnFuncionDeAlineacion(
			Boolean orientarPaginaEnFuncionDeAlineacion) {
		this.orientarPaginaEnFuncionDeAlineacion = orientarPaginaEnFuncionDeAlineacion;
	}

	public Boolean getSeleccionDeArchivoAlIndicarReferenciaDocumental() {
		return this.seleccionDeArchivoAlIndicarReferenciaDocumental;
	}

	public void setSeleccionDeArchivoAlIndicarReferenciaDocumental(
			Boolean seleccionDeArchivoAlIndicarReferenciaDocumental) {
		this.seleccionDeArchivoAlIndicarReferenciaDocumental = seleccionDeArchivoAlIndicarReferenciaDocumental;
	}

	public Boolean getVisualizarSugerenciasInicio() {
		return this.visualizarSugerenciasInicio;
	}

	public void setVisualizarSugerenciasInicio(
			Boolean visualizarSugerenciasInicio) {
		this.visualizarSugerenciasInicio = visualizarSugerenciasInicio;
	}

	public Boolean getActivarConsejos() {
		return this.activarConsejos;
	}

	public void setActivarConsejos(Boolean activarConsejos) {
		this.activarConsejos = activarConsejos;
	}

	public Boolean getActivarPanelDeInicio() {
		return this.activarPanelDeInicio;
	}

	public void setActivarPanelDeInicio(Boolean activarPanelDeInicio) {
		this.activarPanelDeInicio = activarPanelDeInicio;
	}

	public Boolean getActivarSeguridad() {
		return this.activarSeguridad;
	}

	public void setActivarSeguridad(Boolean activarSeguridad) {
		this.activarSeguridad = activarSeguridad;
	}

	public Boolean getActivarSeguridadOo() {
		return this.activarSeguridadOo;
	}

	public void setActivarSeguridadOo(Boolean activarSeguridadOo) {
		this.activarSeguridadOo = activarSeguridadOo;
	}

	public Boolean getActivarSeguridadSys() {
		return this.activarSeguridadSys;
	}

	public void setActivarSeguridadSys(Boolean activarSeguridadSys) {
		this.activarSeguridadSys = activarSeguridadSys;
	}

}
