package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoRefs generated by hbm2java
 */
public class OoRefs implements java.io.Serializable {

	private OoRefsId id;

	public OoRefs() {
	}

	public OoRefs(OoRefsId id) {
		this.id = id;
	}

	public OoRefsId getId() {
		return this.id;
	}

	public void setId(OoRefsId id) {
		this.id = id;
	}

}
