package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OoReadedId generated by hbm2java
 */
public class OoReadedId implements java.io.Serializable {

	private String gid;
	private String userName;
	private Date readedDate;

	public OoReadedId() {
	}

	public OoReadedId(Date readedDate) {
		this.readedDate = readedDate;
	}

	public OoReadedId(String gid, String userName, Date readedDate) {
		this.gid = gid;
		this.userName = userName;
		this.readedDate = readedDate;
	}

	public String getGid() {
		return this.gid;
	}

	public void setGid(String gid) {
		this.gid = gid;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Date getReadedDate() {
		return this.readedDate;
	}

	public void setReadedDate(Date readedDate) {
		this.readedDate = readedDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OoReadedId))
			return false;
		OoReadedId castOther = (OoReadedId) other;

		return ((this.getGid() == castOther.getGid()) || (this.getGid() != null
				&& castOther.getGid() != null && this.getGid().equals(
				castOther.getGid())))
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())))
				&& ((this.getReadedDate() == castOther.getReadedDate()) || (this
						.getReadedDate() != null
						&& castOther.getReadedDate() != null && this
						.getReadedDate().equals(castOther.getReadedDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGid() == null ? 0 : this.getGid().hashCode());
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37
				* result
				+ (getReadedDate() == null ? 0 : this.getReadedDate()
						.hashCode());
		return result;
	}

}
