package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoReaded generated by hbm2java
 */
public class OoReaded implements java.io.Serializable {

	private OoReadedId id;

	public OoReaded() {
	}

	public OoReaded(OoReadedId id) {
		this.id = id;
	}

	public OoReadedId getId() {
		return this.id;
	}

	public void setId(OoReadedId id) {
		this.id = id;
	}

}
