package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OoSgcauditPreguntas generated by hbm2java
 */
public class OoSgcauditPreguntas implements java.io.Serializable {

	private Integer idx;
	private String apauditId;
	private int apestado;
	private String appregunta;
	private Integer aptipo;
	private String apconstatacion;
	private String apprueba;
	private String appruebaFile;
	private String apconclusion;
	private String apuserCreate;
	private Date apfechaCreacion;
	private Date apfechaCierre;

	public OoSgcauditPreguntas() {
	}

	public OoSgcauditPreguntas(String apauditId, int apestado, String appregunta) {
		this.apauditId = apauditId;
		this.apestado = apestado;
		this.appregunta = appregunta;
	}

	public OoSgcauditPreguntas(String apauditId, int apestado,
			String appregunta, Integer aptipo, String apconstatacion,
			String apprueba, String appruebaFile, String apconclusion,
			String apuserCreate, Date apfechaCreacion, Date apfechaCierre) {
		this.apauditId = apauditId;
		this.apestado = apestado;
		this.appregunta = appregunta;
		this.aptipo = aptipo;
		this.apconstatacion = apconstatacion;
		this.apprueba = apprueba;
		this.appruebaFile = appruebaFile;
		this.apconclusion = apconclusion;
		this.apuserCreate = apuserCreate;
		this.apfechaCreacion = apfechaCreacion;
		this.apfechaCierre = apfechaCierre;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getApauditId() {
		return this.apauditId;
	}

	public void setApauditId(String apauditId) {
		this.apauditId = apauditId;
	}

	public int getApestado() {
		return this.apestado;
	}

	public void setApestado(int apestado) {
		this.apestado = apestado;
	}

	public String getAppregunta() {
		return this.appregunta;
	}

	public void setAppregunta(String appregunta) {
		this.appregunta = appregunta;
	}

	public Integer getAptipo() {
		return this.aptipo;
	}

	public void setAptipo(Integer aptipo) {
		this.aptipo = aptipo;
	}

	public String getApconstatacion() {
		return this.apconstatacion;
	}

	public void setApconstatacion(String apconstatacion) {
		this.apconstatacion = apconstatacion;
	}

	public String getApprueba() {
		return this.apprueba;
	}

	public void setApprueba(String apprueba) {
		this.apprueba = apprueba;
	}

	public String getAppruebaFile() {
		return this.appruebaFile;
	}

	public void setAppruebaFile(String appruebaFile) {
		this.appruebaFile = appruebaFile;
	}

	public String getApconclusion() {
		return this.apconclusion;
	}

	public void setApconclusion(String apconclusion) {
		this.apconclusion = apconclusion;
	}

	public String getApuserCreate() {
		return this.apuserCreate;
	}

	public void setApuserCreate(String apuserCreate) {
		this.apuserCreate = apuserCreate;
	}

	public Date getApfechaCreacion() {
		return this.apfechaCreacion;
	}

	public void setApfechaCreacion(Date apfechaCreacion) {
		this.apfechaCreacion = apfechaCreacion;
	}

	public Date getApfechaCierre() {
		return this.apfechaCierre;
	}

	public void setApfechaCierre(Date apfechaCierre) {
		this.apfechaCierre = apfechaCierre;
	}

}
