package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OoSgcdesviacion generated by hbm2java
 */
public class OoSgcdesviacion implements java.io.Serializable {

	private String idx;
	private int destado;
	private Date dfechaCreacion;
	private String dsistema;
	private String dsitio;
	private String dproceso;
	private String dproducto;
	private String dproveedor;
	private String dactividad;
	private String dservicio;
	private String dtipoDesviacion;
	private String dcliente;
	private String ddescripcion;
	private String drespAnalisis;
	private String drespDecision;
	private Integer dhoras;
	private Date dfechaPrevista;
	private String dautor;
	private String dparentId;
	private Integer dparentLineaId;
	private Date danaFecha;
	private String danaTxt;
	private Integer danaHoras;
	private String ddesDecision;
	private String ddesTxt;
	private Integer ddesHoras;

	public OoSgcdesviacion() {
	}

	public OoSgcdesviacion(String idx, int destado) {
		this.idx = idx;
		this.destado = destado;
	}

	public OoSgcdesviacion(String idx, int destado, Date dfechaCreacion,
			String dsistema, String dsitio, String dproceso, String dproducto,
			String dproveedor, String dactividad, String dservicio,
			String dtipoDesviacion, String dcliente, String ddescripcion,
			String drespAnalisis, String drespDecision, Integer dhoras,
			Date dfechaPrevista, String dautor, String dparentId,
			Integer dparentLineaId, Date danaFecha, String danaTxt,
			Integer danaHoras, String ddesDecision, String ddesTxt,
			Integer ddesHoras) {
		this.idx = idx;
		this.destado = destado;
		this.dfechaCreacion = dfechaCreacion;
		this.dsistema = dsistema;
		this.dsitio = dsitio;
		this.dproceso = dproceso;
		this.dproducto = dproducto;
		this.dproveedor = dproveedor;
		this.dactividad = dactividad;
		this.dservicio = dservicio;
		this.dtipoDesviacion = dtipoDesviacion;
		this.dcliente = dcliente;
		this.ddescripcion = ddescripcion;
		this.drespAnalisis = drespAnalisis;
		this.drespDecision = drespDecision;
		this.dhoras = dhoras;
		this.dfechaPrevista = dfechaPrevista;
		this.dautor = dautor;
		this.dparentId = dparentId;
		this.dparentLineaId = dparentLineaId;
		this.danaFecha = danaFecha;
		this.danaTxt = danaTxt;
		this.danaHoras = danaHoras;
		this.ddesDecision = ddesDecision;
		this.ddesTxt = ddesTxt;
		this.ddesHoras = ddesHoras;
	}

	public String getIdx() {
		return this.idx;
	}

	public void setIdx(String idx) {
		this.idx = idx;
	}

	public int getDestado() {
		return this.destado;
	}

	public void setDestado(int destado) {
		this.destado = destado;
	}

	public Date getDfechaCreacion() {
		return this.dfechaCreacion;
	}

	public void setDfechaCreacion(Date dfechaCreacion) {
		this.dfechaCreacion = dfechaCreacion;
	}

	public String getDsistema() {
		return this.dsistema;
	}

	public void setDsistema(String dsistema) {
		this.dsistema = dsistema;
	}

	public String getDsitio() {
		return this.dsitio;
	}

	public void setDsitio(String dsitio) {
		this.dsitio = dsitio;
	}

	public String getDproceso() {
		return this.dproceso;
	}

	public void setDproceso(String dproceso) {
		this.dproceso = dproceso;
	}

	public String getDproducto() {
		return this.dproducto;
	}

	public void setDproducto(String dproducto) {
		this.dproducto = dproducto;
	}

	public String getDproveedor() {
		return this.dproveedor;
	}

	public void setDproveedor(String dproveedor) {
		this.dproveedor = dproveedor;
	}

	public String getDactividad() {
		return this.dactividad;
	}

	public void setDactividad(String dactividad) {
		this.dactividad = dactividad;
	}

	public String getDservicio() {
		return this.dservicio;
	}

	public void setDservicio(String dservicio) {
		this.dservicio = dservicio;
	}

	public String getDtipoDesviacion() {
		return this.dtipoDesviacion;
	}

	public void setDtipoDesviacion(String dtipoDesviacion) {
		this.dtipoDesviacion = dtipoDesviacion;
	}

	public String getDcliente() {
		return this.dcliente;
	}

	public void setDcliente(String dcliente) {
		this.dcliente = dcliente;
	}

	public String getDdescripcion() {
		return this.ddescripcion;
	}

	public void setDdescripcion(String ddescripcion) {
		this.ddescripcion = ddescripcion;
	}

	public String getDrespAnalisis() {
		return this.drespAnalisis;
	}

	public void setDrespAnalisis(String drespAnalisis) {
		this.drespAnalisis = drespAnalisis;
	}

	public String getDrespDecision() {
		return this.drespDecision;
	}

	public void setDrespDecision(String drespDecision) {
		this.drespDecision = drespDecision;
	}

	public Integer getDhoras() {
		return this.dhoras;
	}

	public void setDhoras(Integer dhoras) {
		this.dhoras = dhoras;
	}

	public Date getDfechaPrevista() {
		return this.dfechaPrevista;
	}

	public void setDfechaPrevista(Date dfechaPrevista) {
		this.dfechaPrevista = dfechaPrevista;
	}

	public String getDautor() {
		return this.dautor;
	}

	public void setDautor(String dautor) {
		this.dautor = dautor;
	}

	public String getDparentId() {
		return this.dparentId;
	}

	public void setDparentId(String dparentId) {
		this.dparentId = dparentId;
	}

	public Integer getDparentLineaId() {
		return this.dparentLineaId;
	}

	public void setDparentLineaId(Integer dparentLineaId) {
		this.dparentLineaId = dparentLineaId;
	}

	public Date getDanaFecha() {
		return this.danaFecha;
	}

	public void setDanaFecha(Date danaFecha) {
		this.danaFecha = danaFecha;
	}

	public String getDanaTxt() {
		return this.danaTxt;
	}

	public void setDanaTxt(String danaTxt) {
		this.danaTxt = danaTxt;
	}

	public Integer getDanaHoras() {
		return this.danaHoras;
	}

	public void setDanaHoras(Integer danaHoras) {
		this.danaHoras = danaHoras;
	}

	public String getDdesDecision() {
		return this.ddesDecision;
	}

	public void setDdesDecision(String ddesDecision) {
		this.ddesDecision = ddesDecision;
	}

	public String getDdesTxt() {
		return this.ddesTxt;
	}

	public void setDdesTxt(String ddesTxt) {
		this.ddesTxt = ddesTxt;
	}

	public Integer getDdesHoras() {
		return this.ddesHoras;
	}

	public void setDdesHoras(Integer ddesHoras) {
		this.ddesHoras = ddesHoras;
	}

}
