package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoSgccompetencias generated by hbm2java
 */
public class OoSgccompetencias implements java.io.Serializable {

	private Integer idx;
	private String ctitulo;
	private String cdescripcion;
	private String ctipoDato;
	private String cidRol;
	private Integer corden;

	public OoSgccompetencias() {
	}

	public OoSgccompetencias(String cidRol) {
		this.cidRol = cidRol;
	}

	public OoSgccompetencias(String ctitulo, String cdescripcion,
			String ctipoDato, String cidRol, Integer corden) {
		this.ctitulo = ctitulo;
		this.cdescripcion = cdescripcion;
		this.ctipoDato = ctipoDato;
		this.cidRol = cidRol;
		this.corden = corden;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getCtitulo() {
		return this.ctitulo;
	}

	public void setCtitulo(String ctitulo) {
		this.ctitulo = ctitulo;
	}

	public String getCdescripcion() {
		return this.cdescripcion;
	}

	public void setCdescripcion(String cdescripcion) {
		this.cdescripcion = cdescripcion;
	}

	public String getCtipoDato() {
		return this.ctipoDato;
	}

	public void setCtipoDato(String ctipoDato) {
		this.ctipoDato = ctipoDato;
	}

	public String getCidRol() {
		return this.cidRol;
	}

	public void setCidRol(String cidRol) {
		this.cidRol = cidRol;
	}

	public Integer getCorden() {
		return this.corden;
	}

	public void setCorden(Integer corden) {
		this.corden = corden;
	}

}
