package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoSgcmasterSitio generated by hbm2java
 */
public class OoSgcmasterSitio implements java.io.Serializable {

	private Integer idx;
	private String sname;
	private String sdescription;

	public OoSgcmasterSitio() {
	}

	public OoSgcmasterSitio(String sname, String sdescription) {
		this.sname = sname;
		this.sdescription = sdescription;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSdescription() {
		return this.sdescription;
	}

	public void setSdescription(String sdescription) {
		this.sdescription = sdescription;
	}

}
