package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoSgctipoMedio generated by hbm2java
 */
public class OoSgctipoMedio implements java.io.Serializable {

	private Integer idx;
	private String mname;
	private String mdescription;

	public OoSgctipoMedio() {
	}

	public OoSgctipoMedio(String mname, String mdescription) {
		this.mname = mname;
		this.mdescription = mdescription;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	public String getMdescription() {
		return this.mdescription;
	}

	public void setMdescription(String mdescription) {
		this.mdescription = mdescription;
	}

}
