package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoSgcmasterActividadId generated by hbm2java
 */
public class OoSgcmasterActividadId implements java.io.Serializable {

	private int idx;
	private String aname;

	public OoSgcmasterActividadId() {
	}

	public OoSgcmasterActividadId(int idx, String aname) {
		this.idx = idx;
		this.aname = aname;
	}

	public int getIdx() {
		return this.idx;
	}

	public void setIdx(int idx) {
		this.idx = idx;
	}

	public String getAname() {
		return this.aname;
	}

	public void setAname(String aname) {
		this.aname = aname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OoSgcmasterActividadId))
			return false;
		OoSgcmasterActividadId castOther = (OoSgcmasterActividadId) other;

		return (this.getIdx() == castOther.getIdx())
				&& ((this.getAname() == castOther.getAname()) || (this
						.getAname() != null
						&& castOther.getAname() != null && this.getAname()
						.equals(castOther.getAname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdx();
		result = 37 * result
				+ (getAname() == null ? 0 : this.getAname().hashCode());
		return result;
	}

}
