package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OoSgcplanAccion generated by hbm2java
 */
public class OoSgcplanAccion implements java.io.Serializable {

	private String idx;
	private String paidAudit;
	private String paidDesviacion;
	private String paidResolucion;
	private String paidOportunidad;
	private String paproceso;
	private String parespProceso;
	private Integer paparentTipo;
	private String paparentEnunciado;
	private String paparentRespAnalisis;
	private String paparentRespDesviacion;
	private String paparentDescAnalisis;
	private String paparentDescDesviacion;
	private String paparentDecision;
	private String paresolucionCausa;
	private String paresolucionSolucion;
	private String paresponsable;
	private String patipoAccion;
	private Date pafechaCreacion;
	private Integer pahoras;
	private Integer paestado;
	private String paautor;
	private String paactividad;
	private String pacliente;
	private String pasistema;
	private String pasitio;
	private String paproducto;
	private String paservicio;
	private String padescripcion;
	private String paproveedor;
	private String paparentTipoParent;
	private Date pafechaPrevistaIni;
	private Date pafechaPrevistaFin;
	private Date pafechaCierre;

	public OoSgcplanAccion() {
	}

	public OoSgcplanAccion(String idx) {
		this.idx = idx;
	}

	public OoSgcplanAccion(String idx, String paidAudit, String paidDesviacion,
			String paidResolucion, String paidOportunidad, String paproceso,
			String parespProceso, Integer paparentTipo,
			String paparentEnunciado, String paparentRespAnalisis,
			String paparentRespDesviacion, String paparentDescAnalisis,
			String paparentDescDesviacion, String paparentDecision,
			String paresolucionCausa, String paresolucionSolucion,
			String paresponsable, String patipoAccion, Date pafechaCreacion,
			Integer pahoras, Integer paestado, String paautor,
			String paactividad, String pacliente, String pasistema,
			String pasitio, String paproducto, String paservicio,
			String padescripcion, String paproveedor,
			String paparentTipoParent, Date pafechaPrevistaIni,
			Date pafechaPrevistaFin, Date pafechaCierre) {
		this.idx = idx;
		this.paidAudit = paidAudit;
		this.paidDesviacion = paidDesviacion;
		this.paidResolucion = paidResolucion;
		this.paidOportunidad = paidOportunidad;
		this.paproceso = paproceso;
		this.parespProceso = parespProceso;
		this.paparentTipo = paparentTipo;
		this.paparentEnunciado = paparentEnunciado;
		this.paparentRespAnalisis = paparentRespAnalisis;
		this.paparentRespDesviacion = paparentRespDesviacion;
		this.paparentDescAnalisis = paparentDescAnalisis;
		this.paparentDescDesviacion = paparentDescDesviacion;
		this.paparentDecision = paparentDecision;
		this.paresolucionCausa = paresolucionCausa;
		this.paresolucionSolucion = paresolucionSolucion;
		this.paresponsable = paresponsable;
		this.patipoAccion = patipoAccion;
		this.pafechaCreacion = pafechaCreacion;
		this.pahoras = pahoras;
		this.paestado = paestado;
		this.paautor = paautor;
		this.paactividad = paactividad;
		this.pacliente = pacliente;
		this.pasistema = pasistema;
		this.pasitio = pasitio;
		this.paproducto = paproducto;
		this.paservicio = paservicio;
		this.padescripcion = padescripcion;
		this.paproveedor = paproveedor;
		this.paparentTipoParent = paparentTipoParent;
		this.pafechaPrevistaIni = pafechaPrevistaIni;
		this.pafechaPrevistaFin = pafechaPrevistaFin;
		this.pafechaCierre = pafechaCierre;
	}

	public String getIdx() {
		return this.idx;
	}

	public void setIdx(String idx) {
		this.idx = idx;
	}

	public String getPaidAudit() {
		return this.paidAudit;
	}

	public void setPaidAudit(String paidAudit) {
		this.paidAudit = paidAudit;
	}

	public String getPaidDesviacion() {
		return this.paidDesviacion;
	}

	public void setPaidDesviacion(String paidDesviacion) {
		this.paidDesviacion = paidDesviacion;
	}

	public String getPaidResolucion() {
		return this.paidResolucion;
	}

	public void setPaidResolucion(String paidResolucion) {
		this.paidResolucion = paidResolucion;
	}

	public String getPaidOportunidad() {
		return this.paidOportunidad;
	}

	public void setPaidOportunidad(String paidOportunidad) {
		this.paidOportunidad = paidOportunidad;
	}

	public String getPaproceso() {
		return this.paproceso;
	}

	public void setPaproceso(String paproceso) {
		this.paproceso = paproceso;
	}

	public String getParespProceso() {
		return this.parespProceso;
	}

	public void setParespProceso(String parespProceso) {
		this.parespProceso = parespProceso;
	}

	public Integer getPaparentTipo() {
		return this.paparentTipo;
	}

	public void setPaparentTipo(Integer paparentTipo) {
		this.paparentTipo = paparentTipo;
	}

	public String getPaparentEnunciado() {
		return this.paparentEnunciado;
	}

	public void setPaparentEnunciado(String paparentEnunciado) {
		this.paparentEnunciado = paparentEnunciado;
	}

	public String getPaparentRespAnalisis() {
		return this.paparentRespAnalisis;
	}

	public void setPaparentRespAnalisis(String paparentRespAnalisis) {
		this.paparentRespAnalisis = paparentRespAnalisis;
	}

	public String getPaparentRespDesviacion() {
		return this.paparentRespDesviacion;
	}

	public void setPaparentRespDesviacion(String paparentRespDesviacion) {
		this.paparentRespDesviacion = paparentRespDesviacion;
	}

	public String getPaparentDescAnalisis() {
		return this.paparentDescAnalisis;
	}

	public void setPaparentDescAnalisis(String paparentDescAnalisis) {
		this.paparentDescAnalisis = paparentDescAnalisis;
	}

	public String getPaparentDescDesviacion() {
		return this.paparentDescDesviacion;
	}

	public void setPaparentDescDesviacion(String paparentDescDesviacion) {
		this.paparentDescDesviacion = paparentDescDesviacion;
	}

	public String getPaparentDecision() {
		return this.paparentDecision;
	}

	public void setPaparentDecision(String paparentDecision) {
		this.paparentDecision = paparentDecision;
	}

	public String getParesolucionCausa() {
		return this.paresolucionCausa;
	}

	public void setParesolucionCausa(String paresolucionCausa) {
		this.paresolucionCausa = paresolucionCausa;
	}

	public String getParesolucionSolucion() {
		return this.paresolucionSolucion;
	}

	public void setParesolucionSolucion(String paresolucionSolucion) {
		this.paresolucionSolucion = paresolucionSolucion;
	}

	public String getParesponsable() {
		return this.paresponsable;
	}

	public void setParesponsable(String paresponsable) {
		this.paresponsable = paresponsable;
	}

	public String getPatipoAccion() {
		return this.patipoAccion;
	}

	public void setPatipoAccion(String patipoAccion) {
		this.patipoAccion = patipoAccion;
	}

	public Date getPafechaCreacion() {
		return this.pafechaCreacion;
	}

	public void setPafechaCreacion(Date pafechaCreacion) {
		this.pafechaCreacion = pafechaCreacion;
	}

	public Integer getPahoras() {
		return this.pahoras;
	}

	public void setPahoras(Integer pahoras) {
		this.pahoras = pahoras;
	}

	public Integer getPaestado() {
		return this.paestado;
	}

	public void setPaestado(Integer paestado) {
		this.paestado = paestado;
	}

	public String getPaautor() {
		return this.paautor;
	}

	public void setPaautor(String paautor) {
		this.paautor = paautor;
	}

	public String getPaactividad() {
		return this.paactividad;
	}

	public void setPaactividad(String paactividad) {
		this.paactividad = paactividad;
	}

	public String getPacliente() {
		return this.pacliente;
	}

	public void setPacliente(String pacliente) {
		this.pacliente = pacliente;
	}

	public String getPasistema() {
		return this.pasistema;
	}

	public void setPasistema(String pasistema) {
		this.pasistema = pasistema;
	}

	public String getPasitio() {
		return this.pasitio;
	}

	public void setPasitio(String pasitio) {
		this.pasitio = pasitio;
	}

	public String getPaproducto() {
		return this.paproducto;
	}

	public void setPaproducto(String paproducto) {
		this.paproducto = paproducto;
	}

	public String getPaservicio() {
		return this.paservicio;
	}

	public void setPaservicio(String paservicio) {
		this.paservicio = paservicio;
	}

	public String getPadescripcion() {
		return this.padescripcion;
	}

	public void setPadescripcion(String padescripcion) {
		this.padescripcion = padescripcion;
	}

	public String getPaproveedor() {
		return this.paproveedor;
	}

	public void setPaproveedor(String paproveedor) {
		this.paproveedor = paproveedor;
	}

	public String getPaparentTipoParent() {
		return this.paparentTipoParent;
	}

	public void setPaparentTipoParent(String paparentTipoParent) {
		this.paparentTipoParent = paparentTipoParent;
	}

	public Date getPafechaPrevistaIni() {
		return this.pafechaPrevistaIni;
	}

	public void setPafechaPrevistaIni(Date pafechaPrevistaIni) {
		this.pafechaPrevistaIni = pafechaPrevistaIni;
	}

	public Date getPafechaPrevistaFin() {
		return this.pafechaPrevistaFin;
	}

	public void setPafechaPrevistaFin(Date pafechaPrevistaFin) {
		this.pafechaPrevistaFin = pafechaPrevistaFin;
	}

	public Date getPafechaCierre() {
		return this.pafechaCierre;
	}

	public void setPafechaCierre(Date pafechaCierre) {
		this.pafechaCierre = pafechaCierre;
	}

}
