package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoSgcpermisos generated by hbm2java
 */
public class OoSgcpermisos implements java.io.Serializable {

	private Integer idx;
	private String prolId;
	private String pmenuLangKey;
	private Integer pc1;
	private Integer pc2;
	private Integer pc3;
	private Integer pm1;
	private Integer pm2;
	private Integer pm3;
	private Integer porder;
	private Boolean pisMainMenu;

	public OoSgcpermisos() {
	}

	public OoSgcpermisos(String prolId, String pmenuLangKey) {
		this.prolId = prolId;
		this.pmenuLangKey = pmenuLangKey;
	}

	public OoSgcpermisos(String prolId, String pmenuLangKey, Integer pc1,
			Integer pc2, Integer pc3, Integer pm1, Integer pm2, Integer pm3,
			Integer porder, Boolean pisMainMenu) {
		this.prolId = prolId;
		this.pmenuLangKey = pmenuLangKey;
		this.pc1 = pc1;
		this.pc2 = pc2;
		this.pc3 = pc3;
		this.pm1 = pm1;
		this.pm2 = pm2;
		this.pm3 = pm3;
		this.porder = porder;
		this.pisMainMenu = pisMainMenu;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getProlId() {
		return this.prolId;
	}

	public void setProlId(String prolId) {
		this.prolId = prolId;
	}

	public String getPmenuLangKey() {
		return this.pmenuLangKey;
	}

	public void setPmenuLangKey(String pmenuLangKey) {
		this.pmenuLangKey = pmenuLangKey;
	}

	public Integer getPc1() {
		return this.pc1;
	}

	public void setPc1(Integer pc1) {
		this.pc1 = pc1;
	}

	public Integer getPc2() {
		return this.pc2;
	}

	public void setPc2(Integer pc2) {
		this.pc2 = pc2;
	}

	public Integer getPc3() {
		return this.pc3;
	}

	public void setPc3(Integer pc3) {
		this.pc3 = pc3;
	}

	public Integer getPm1() {
		return this.pm1;
	}

	public void setPm1(Integer pm1) {
		this.pm1 = pm1;
	}

	public Integer getPm2() {
		return this.pm2;
	}

	public void setPm2(Integer pm2) {
		this.pm2 = pm2;
	}

	public Integer getPm3() {
		return this.pm3;
	}

	public void setPm3(Integer pm3) {
		this.pm3 = pm3;
	}

	public Integer getPorder() {
		return this.porder;
	}

	public void setPorder(Integer porder) {
		this.porder = porder;
	}

	public Boolean getPisMainMenu() {
		return this.pisMainMenu;
	}

	public void setPisMainMenu(Boolean pisMainMenu) {
		this.pisMainMenu = pisMainMenu;
	}

}
