package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoSgctipoDesviacion generated by hbm2java
 */
public class OoSgctipoDesviacion implements java.io.Serializable {

	private Integer idx;
	private String tdname;
	private String tddescription;

	public OoSgctipoDesviacion() {
	}

	public OoSgctipoDesviacion(String tdname, String tddescription) {
		this.tdname = tdname;
		this.tddescription = tddescription;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getTdname() {
		return this.tdname;
	}

	public void setTdname(String tdname) {
		this.tdname = tdname;
	}

	public String getTddescription() {
		return this.tddescription;
	}

	public void setTddescription(String tddescription) {
		this.tddescription = tddescription;
	}

}
