package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OoSgcauditCriterios generated by hbm2java
 */
public class OoSgcauditCriterios implements java.io.Serializable {

	private Integer idx;
	private String acauditId;
	private String actitulo;
	private Integer actipo;
	private String acurl;
	private String acarchivo;
	private Date acfecha;

	public OoSgcauditCriterios() {
	}

	public OoSgcauditCriterios(String acauditId, Date acfecha) {
		this.acauditId = acauditId;
		this.acfecha = acfecha;
	}

	public OoSgcauditCriterios(String acauditId, String actitulo,
			Integer actipo, String acurl, String acarchivo, Date acfecha) {
		this.acauditId = acauditId;
		this.actitulo = actitulo;
		this.actipo = actipo;
		this.acurl = acurl;
		this.acarchivo = acarchivo;
		this.acfecha = acfecha;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getAcauditId() {
		return this.acauditId;
	}

	public void setAcauditId(String acauditId) {
		this.acauditId = acauditId;
	}

	public String getActitulo() {
		return this.actitulo;
	}

	public void setActitulo(String actitulo) {
		this.actitulo = actitulo;
	}

	public Integer getActipo() {
		return this.actipo;
	}

	public void setActipo(Integer actipo) {
		this.actipo = actipo;
	}

	public String getAcurl() {
		return this.acurl;
	}

	public void setAcurl(String acurl) {
		this.acurl = acurl;
	}

	public String getAcarchivo() {
		return this.acarchivo;
	}

	public void setAcarchivo(String acarchivo) {
		this.acarchivo = acarchivo;
	}

	public Date getAcfecha() {
		return this.acfecha;
	}

	public void setAcfecha(Date acfecha) {
		this.acfecha = acfecha;
	}

}
