package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoSgcmasterCliente generated by hbm2java
 */
public class OoSgcmasterCliente implements java.io.Serializable {

	private Integer idx;
	private String cname;
	private String cdescription;

	public OoSgcmasterCliente() {
	}

	public OoSgcmasterCliente(String cname, String cdescription) {
		this.cname = cname;
		this.cdescription = cdescription;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getCdescription() {
		return this.cdescription;
	}

	public void setCdescription(String cdescription) {
		this.cdescription = cdescription;
	}

}
