package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoSgcmasterActividad generated by hbm2java
 */
public class OoSgcmasterActividad implements java.io.Serializable {

	private OoSgcmasterActividadId id;
	private String adescription;

	public OoSgcmasterActividad() {
	}

	public OoSgcmasterActividad(OoSgcmasterActividadId id) {
		this.id = id;
	}

	public OoSgcmasterActividad(OoSgcmasterActividadId id, String adescription) {
		this.id = id;
		this.adescription = adescription;
	}

	public OoSgcmasterActividadId getId() {
		return this.id;
	}

	public void setId(OoSgcmasterActividadId id) {
		this.id = id;
	}

	public String getAdescription() {
		return this.adescription;
	}

	public void setAdescription(String adescription) {
		this.adescription = adescription;
	}

}
