package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoSgcnotify generated by hbm2java
 */
public class OoSgcnotify implements java.io.Serializable {

	private Integer idx;
	private String ndescripcion;
	private Integer ntipo;
	private String nuser;
	private Integer nidRemoto;
	private String nstringIdRemoto;

	public OoSgcnotify() {
	}

	public OoSgcnotify(String ndescripcion, Integer ntipo, String nuser,
			Integer nidRemoto, String nstringIdRemoto) {
		this.ndescripcion = ndescripcion;
		this.ntipo = ntipo;
		this.nuser = nuser;
		this.nidRemoto = nidRemoto;
		this.nstringIdRemoto = nstringIdRemoto;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getNdescripcion() {
		return this.ndescripcion;
	}

	public void setNdescripcion(String ndescripcion) {
		this.ndescripcion = ndescripcion;
	}

	public Integer getNtipo() {
		return this.ntipo;
	}

	public void setNtipo(Integer ntipo) {
		this.ntipo = ntipo;
	}

	public String getNuser() {
		return this.nuser;
	}

	public void setNuser(String nuser) {
		this.nuser = nuser;
	}

	public Integer getNidRemoto() {
		return this.nidRemoto;
	}

	public void setNidRemoto(Integer nidRemoto) {
		this.nidRemoto = nidRemoto;
	}

	public String getNstringIdRemoto() {
		return this.nstringIdRemoto;
	}

	public void setNstringIdRemoto(String nstringIdRemoto) {
		this.nstringIdRemoto = nstringIdRemoto;
	}

}
