package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OoSgcplanAccionLinea generated by hbm2java
 */
public class OoSgcplanAccionLinea implements java.io.Serializable {

	private Integer idx;
	private String palidPa;
	private Integer palestado;
	private String palque;
	private String palquien;
	private String paldonde;
	private String palcomo;
	private String palcuando;
	private String palcuanto;
	private String palarchivo;
	private String palautor;
	private Date palfechaCreacion;
	private Date palfechaPrevInicio;
	private Date palfechaPrevFin;
	private Date palfechaCierre;

	public OoSgcplanAccionLinea() {
	}

	public OoSgcplanAccionLinea(String palidPa) {
		this.palidPa = palidPa;
	}

	public OoSgcplanAccionLinea(String palidPa, Integer palestado,
			String palque, String palquien, String paldonde, String palcomo,
			String palcuando, String palcuanto, String palarchivo,
			String palautor, Date palfechaCreacion, Date palfechaPrevInicio,
			Date palfechaPrevFin, Date palfechaCierre) {
		this.palidPa = palidPa;
		this.palestado = palestado;
		this.palque = palque;
		this.palquien = palquien;
		this.paldonde = paldonde;
		this.palcomo = palcomo;
		this.palcuando = palcuando;
		this.palcuanto = palcuanto;
		this.palarchivo = palarchivo;
		this.palautor = palautor;
		this.palfechaCreacion = palfechaCreacion;
		this.palfechaPrevInicio = palfechaPrevInicio;
		this.palfechaPrevFin = palfechaPrevFin;
		this.palfechaCierre = palfechaCierre;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getPalidPa() {
		return this.palidPa;
	}

	public void setPalidPa(String palidPa) {
		this.palidPa = palidPa;
	}

	public Integer getPalestado() {
		return this.palestado;
	}

	public void setPalestado(Integer palestado) {
		this.palestado = palestado;
	}

	public String getPalque() {
		return this.palque;
	}

	public void setPalque(String palque) {
		this.palque = palque;
	}

	public String getPalquien() {
		return this.palquien;
	}

	public void setPalquien(String palquien) {
		this.palquien = palquien;
	}

	public String getPaldonde() {
		return this.paldonde;
	}

	public void setPaldonde(String paldonde) {
		this.paldonde = paldonde;
	}

	public String getPalcomo() {
		return this.palcomo;
	}

	public void setPalcomo(String palcomo) {
		this.palcomo = palcomo;
	}

	public String getPalcuando() {
		return this.palcuando;
	}

	public void setPalcuando(String palcuando) {
		this.palcuando = palcuando;
	}

	public String getPalcuanto() {
		return this.palcuanto;
	}

	public void setPalcuanto(String palcuanto) {
		this.palcuanto = palcuanto;
	}

	public String getPalarchivo() {
		return this.palarchivo;
	}

	public void setPalarchivo(String palarchivo) {
		this.palarchivo = palarchivo;
	}

	public String getPalautor() {
		return this.palautor;
	}

	public void setPalautor(String palautor) {
		this.palautor = palautor;
	}

	public Date getPalfechaCreacion() {
		return this.palfechaCreacion;
	}

	public void setPalfechaCreacion(Date palfechaCreacion) {
		this.palfechaCreacion = palfechaCreacion;
	}

	public Date getPalfechaPrevInicio() {
		return this.palfechaPrevInicio;
	}

	public void setPalfechaPrevInicio(Date palfechaPrevInicio) {
		this.palfechaPrevInicio = palfechaPrevInicio;
	}

	public Date getPalfechaPrevFin() {
		return this.palfechaPrevFin;
	}

	public void setPalfechaPrevFin(Date palfechaPrevFin) {
		this.palfechaPrevFin = palfechaPrevFin;
	}

	public Date getPalfechaCierre() {
		return this.palfechaCierre;
	}

	public void setPalfechaCierre(Date palfechaCierre) {
		this.palfechaCierre = palfechaCierre;
	}

}
