package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoSgctipoOportunidad generated by hbm2java
 */
public class OoSgctipoOportunidad implements java.io.Serializable {

	private Integer idx;
	private String toname;
	private String todescription;

	public OoSgctipoOportunidad() {
	}

	public OoSgctipoOportunidad(String toname, String todescription) {
		this.toname = toname;
		this.todescription = todescription;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getToname() {
		return this.toname;
	}

	public void setToname(String toname) {
		this.toname = toname;
	}

	public String getTodescription() {
		return this.todescription;
	}

	public void setTodescription(String todescription) {
		this.todescription = todescription;
	}

}
