package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * OoSgccapacitacion generated by hbm2java
 */
public class OoSgccapacitacion implements java.io.Serializable {

	private Integer idx;
	private String ctitulo;
	private String cdescripcion;
	private String cidRol;
	private Integer cescalaValoracion;
	private Integer cvaloracion;

	public OoSgccapacitacion() {
	}

	public OoSgccapacitacion(String ctitulo, String cdescripcion,
			String cidRol, Integer cescalaValoracion, Integer cvaloracion) {
		this.ctitulo = ctitulo;
		this.cdescripcion = cdescripcion;
		this.cidRol = cidRol;
		this.cescalaValoracion = cescalaValoracion;
		this.cvaloracion = cvaloracion;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getCtitulo() {
		return this.ctitulo;
	}

	public void setCtitulo(String ctitulo) {
		this.ctitulo = ctitulo;
	}

	public String getCdescripcion() {
		return this.cdescripcion;
	}

	public void setCdescripcion(String cdescripcion) {
		this.cdescripcion = cdescripcion;
	}

	public String getCidRol() {
		return this.cidRol;
	}

	public void setCidRol(String cidRol) {
		this.cidRol = cidRol;
	}

	public Integer getCescalaValoracion() {
		return this.cescalaValoracion;
	}

	public void setCescalaValoracion(Integer cescalaValoracion) {
		this.cescalaValoracion = cescalaValoracion;
	}

	public Integer getCvaloracion() {
		return this.cvaloracion;
	}

	public void setCvaloracion(Integer cvaloracion) {
		this.cvaloracion = cvaloracion;
	}

}
