package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Prefixes generated by hbm2java
 */
public class Prefixes implements java.io.Serializable {

	private PrefixesId id;

	public Prefixes() {
	}

	public Prefixes(PrefixesId id) {
		this.id = id;
	}

	public PrefixesId getId() {
		return this.id;
	}

	public void setId(PrefixesId id) {
		this.id = id;
	}

}
