package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * PrefixesId generated by hbm2java
 */
public class PrefixesId implements java.io.Serializable {

	private String prefixeAction;
	private String prefixeAudit;
	private String prefixeIncident;
	private int indiceAction;
	private int indiceAudit;
	private int indiceIncident;
	private Integer prefixe;
	private int autorisation;

	public PrefixesId() {
	}

	public PrefixesId(String prefixeAction, String prefixeAudit,
			String prefixeIncident, int indiceAction, int indiceAudit,
			int indiceIncident, int autorisation) {
		this.prefixeAction = prefixeAction;
		this.prefixeAudit = prefixeAudit;
		this.prefixeIncident = prefixeIncident;
		this.indiceAction = indiceAction;
		this.indiceAudit = indiceAudit;
		this.indiceIncident = indiceIncident;
		this.autorisation = autorisation;
	}

	public PrefixesId(String prefixeAction, String prefixeAudit,
			String prefixeIncident, int indiceAction, int indiceAudit,
			int indiceIncident, Integer prefixe, int autorisation) {
		this.prefixeAction = prefixeAction;
		this.prefixeAudit = prefixeAudit;
		this.prefixeIncident = prefixeIncident;
		this.indiceAction = indiceAction;
		this.indiceAudit = indiceAudit;
		this.indiceIncident = indiceIncident;
		this.prefixe = prefixe;
		this.autorisation = autorisation;
	}

	public String getPrefixeAction() {
		return this.prefixeAction;
	}

	public void setPrefixeAction(String prefixeAction) {
		this.prefixeAction = prefixeAction;
	}

	public String getPrefixeAudit() {
		return this.prefixeAudit;
	}

	public void setPrefixeAudit(String prefixeAudit) {
		this.prefixeAudit = prefixeAudit;
	}

	public String getPrefixeIncident() {
		return this.prefixeIncident;
	}

	public void setPrefixeIncident(String prefixeIncident) {
		this.prefixeIncident = prefixeIncident;
	}

	public int getIndiceAction() {
		return this.indiceAction;
	}

	public void setIndiceAction(int indiceAction) {
		this.indiceAction = indiceAction;
	}

	public int getIndiceAudit() {
		return this.indiceAudit;
	}

	public void setIndiceAudit(int indiceAudit) {
		this.indiceAudit = indiceAudit;
	}

	public int getIndiceIncident() {
		return this.indiceIncident;
	}

	public void setIndiceIncident(int indiceIncident) {
		this.indiceIncident = indiceIncident;
	}

	public Integer getPrefixe() {
		return this.prefixe;
	}

	public void setPrefixe(Integer prefixe) {
		this.prefixe = prefixe;
	}

	public int getAutorisation() {
		return this.autorisation;
	}

	public void setAutorisation(int autorisation) {
		this.autorisation = autorisation;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrefixesId))
			return false;
		PrefixesId castOther = (PrefixesId) other;

		return ((this.getPrefixeAction() == castOther.getPrefixeAction()) || (this
				.getPrefixeAction() != null
				&& castOther.getPrefixeAction() != null && this
				.getPrefixeAction().equals(castOther.getPrefixeAction())))
				&& ((this.getPrefixeAudit() == castOther.getPrefixeAudit()) || (this
						.getPrefixeAudit() != null
						&& castOther.getPrefixeAudit() != null && this
						.getPrefixeAudit().equals(castOther.getPrefixeAudit())))
				&& ((this.getPrefixeIncident() == castOther
						.getPrefixeIncident()) || (this.getPrefixeIncident() != null
						&& castOther.getPrefixeIncident() != null && this
						.getPrefixeIncident().equals(
								castOther.getPrefixeIncident())))
				&& (this.getIndiceAction() == castOther.getIndiceAction())
				&& (this.getIndiceAudit() == castOther.getIndiceAudit())
				&& (this.getIndiceIncident() == castOther.getIndiceIncident())
				&& ((this.getPrefixe() == castOther.getPrefixe()) || (this
						.getPrefixe() != null
						&& castOther.getPrefixe() != null && this.getPrefixe()
						.equals(castOther.getPrefixe())))
				&& (this.getAutorisation() == castOther.getAutorisation());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPrefixeAction() == null ? 0 : this.getPrefixeAction()
						.hashCode());
		result = 37
				* result
				+ (getPrefixeAudit() == null ? 0 : this.getPrefixeAudit()
						.hashCode());
		result = 37
				* result
				+ (getPrefixeIncident() == null ? 0 : this.getPrefixeIncident()
						.hashCode());
		result = 37 * result + this.getIndiceAction();
		result = 37 * result + this.getIndiceAudit();
		result = 37 * result + this.getIndiceIncident();
		result = 37 * result
				+ (getPrefixe() == null ? 0 : this.getPrefixe().hashCode());
		result = 37 * result + this.getAutorisation();
		return result;
	}

}
