package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblactorslinks generated by hbm2java
 */
public class Tblactorslinks implements java.io.Serializable {

	private TblactorslinksId id;

	public Tblactorslinks() {
	}

	public Tblactorslinks(TblactorslinksId id) {
		this.id = id;
	}

	public TblactorslinksId getId() {
		return this.id;
	}

	public void setId(TblactorslinksId id) {
		this.id = id;
	}

}
