package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblcounters generated by hbm2java
 */
public class Tblcounters implements java.io.Serializable {

	private TblcountersId id;

	public Tblcounters() {
	}

	public Tblcounters(TblcountersId id) {
		this.id = id;
	}

	public TblcountersId getId() {
		return this.id;
	}

	public void setId(TblcountersId id) {
		this.id = id;
	}

}
