package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * TblcountersId generated by hbm2java
 */
public class TblcountersId implements java.io.Serializable {

	private String gsn;
	private String ctype;
	private int cpt;

	public TblcountersId() {
	}

	public TblcountersId(int cpt) {
		this.cpt = cpt;
	}

	public TblcountersId(String gsn, String ctype, int cpt) {
		this.gsn = gsn;
		this.ctype = ctype;
		this.cpt = cpt;
	}

	public String getGsn() {
		return this.gsn;
	}

	public void setGsn(String gsn) {
		this.gsn = gsn;
	}

	public String getCtype() {
		return this.ctype;
	}

	public void setCtype(String ctype) {
		this.ctype = ctype;
	}

	public int getCpt() {
		return this.cpt;
	}

	public void setCpt(int cpt) {
		this.cpt = cpt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblcountersId))
			return false;
		TblcountersId castOther = (TblcountersId) other;

		return ((this.getGsn() == castOther.getGsn()) || (this.getGsn() != null
				&& castOther.getGsn() != null && this.getGsn().equals(
				castOther.getGsn())))
				&& ((this.getCtype() == castOther.getCtype()) || (this
						.getCtype() != null
						&& castOther.getCtype() != null && this.getCtype()
						.equals(castOther.getCtype())))
				&& (this.getCpt() == castOther.getCpt());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGsn() == null ? 0 : this.getGsn().hashCode());
		result = 37 * result
				+ (getCtype() == null ? 0 : this.getCtype().hashCode());
		result = 37 * result + this.getCpt();
		return result;
	}

}
