package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tbldemande generated by hbm2java
 */
public class Tbldemande implements java.io.Serializable {

	private TbldemandeId id;

	public Tbldemande() {
	}

	public Tbldemande(TbldemandeId id) {
		this.id = id;
	}

	public TbldemandeId getId() {
		return this.id;
	}

	public void setId(TbldemandeId id) {
		this.id = id;
	}

}
