package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblextensions generated by hbm2java
 */
public class Tblextensions implements java.io.Serializable {

	private TblextensionsId id;

	public Tblextensions() {
	}

	public Tblextensions(TblextensionsId id) {
		this.id = id;
	}

	public TblextensionsId getId() {
		return this.id;
	}

	public void setId(TblextensionsId id) {
		this.id = id;
	}

}
