package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblentitylinks generated by hbm2java
 */
public class Tblentitylinks implements java.io.Serializable {

	private TblentitylinksId id;

	public Tblentitylinks() {
	}

	public Tblentitylinks(TblentitylinksId id) {
		this.id = id;
	}

	public TblentitylinksId getId() {
		return this.id;
	}

	public void setId(TblentitylinksId id) {
		this.id = id;
	}

}
