package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblentity generated by hbm2java
 */
public class Tblentity implements java.io.Serializable {

	private TblentityId id;

	public Tblentity() {
	}

	public Tblentity(TblentityId id) {
		this.id = id;
	}

	public TblentityId getId() {
		return this.id;
	}

	public void setId(TblentityId id) {
		this.id = id;
	}

}
