package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * TblentitylinksId generated by hbm2java
 */
public class TblentitylinksId implements java.io.Serializable {

	private String gidAv;
	private String gidAm;

	public TblentitylinksId() {
	}

	public TblentitylinksId(String gidAv, String gidAm) {
		this.gidAv = gidAv;
		this.gidAm = gidAm;
	}

	public String getGidAv() {
		return this.gidAv;
	}

	public void setGidAv(String gidAv) {
		this.gidAv = gidAv;
	}

	public String getGidAm() {
		return this.gidAm;
	}

	public void setGidAm(String gidAm) {
		this.gidAm = gidAm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblentitylinksId))
			return false;
		TblentitylinksId castOther = (TblentitylinksId) other;

		return ((this.getGidAv() == castOther.getGidAv()) || (this.getGidAv() != null
				&& castOther.getGidAv() != null && this.getGidAv().equals(
				castOther.getGidAv())))
				&& ((this.getGidAm() == castOther.getGidAm()) || (this
						.getGidAm() != null
						&& castOther.getGidAm() != null && this.getGidAm()
						.equals(castOther.getGidAm())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGidAv() == null ? 0 : this.getGidAv().hashCode());
		result = 37 * result
				+ (getGidAm() == null ? 0 : this.getGidAm().hashCode());
		return result;
	}

}
