package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblextelements generated by hbm2java
 */
public class Tblextelements implements java.io.Serializable {

	private TblextelementsId id;

	public Tblextelements() {
	}

	public Tblextelements(TblextelementsId id) {
		this.id = id;
	}

	public TblextelementsId getId() {
		return this.id;
	}

	public void setId(TblextelementsId id) {
		this.id = id;
	}

}
