package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * TblextensionsId generated by hbm2java
 */
public class TblextensionsId implements java.io.Serializable {

	private String extId;
	private String extDescription;
	private int extType;

	public TblextensionsId() {
	}

	public TblextensionsId(String extDescription, int extType) {
		this.extDescription = extDescription;
		this.extType = extType;
	}

	public TblextensionsId(String extId, String extDescription, int extType) {
		this.extId = extId;
		this.extDescription = extDescription;
		this.extType = extType;
	}

	public String getExtId() {
		return this.extId;
	}

	public void setExtId(String extId) {
		this.extId = extId;
	}

	public String getExtDescription() {
		return this.extDescription;
	}

	public void setExtDescription(String extDescription) {
		this.extDescription = extDescription;
	}

	public int getExtType() {
		return this.extType;
	}

	public void setExtType(int extType) {
		this.extType = extType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblextensionsId))
			return false;
		TblextensionsId castOther = (TblextensionsId) other;

		return ((this.getExtId() == castOther.getExtId()) || (this.getExtId() != null
				&& castOther.getExtId() != null && this.getExtId().equals(
				castOther.getExtId())))
				&& ((this.getExtDescription() == castOther.getExtDescription()) || (this
						.getExtDescription() != null
						&& castOther.getExtDescription() != null && this
						.getExtDescription().equals(
								castOther.getExtDescription())))
				&& (this.getExtType() == castOther.getExtType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getExtId() == null ? 0 : this.getExtId().hashCode());
		result = 37
				* result
				+ (getExtDescription() == null ? 0 : this.getExtDescription()
						.hashCode());
		result = 37 * result + this.getExtType();
		return result;
	}

}
