package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblfavoris generated by hbm2java
 */
public class Tblfavoris implements java.io.Serializable {

	private TblfavorisId id;

	public Tblfavoris() {
	}

	public Tblfavoris(TblfavorisId id) {
		this.id = id;
	}

	public TblfavorisId getId() {
		return this.id;
	}

	public void setId(TblfavorisId id) {
		this.id = id;
	}

}
