package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblfinds generated by hbm2java
 */
public class Tblfinds implements java.io.Serializable {

	private TblfindsId id;

	public Tblfinds() {
	}

	public Tblfinds(TblfindsId id) {
		this.id = id;
	}

	public TblfindsId getId() {
		return this.id;
	}

	public void setId(TblfindsId id) {
		this.id = id;
	}

}
