package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblfield generated by hbm2java
 */
public class Tblfield implements java.io.Serializable {

	private TblfieldId id;

	public Tblfield() {
	}

	public Tblfield(TblfieldId id) {
		this.id = id;
	}

	public TblfieldId getId() {
		return this.id;
	}

	public void setId(TblfieldId id) {
		this.id = id;
	}

}
