package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * TblfavorisId generated by hbm2java
 */
public class TblfavorisId implements java.io.Serializable {

	private String gid;
	private String userName;

	public TblfavorisId() {
	}

	public TblfavorisId(String gid, String userName) {
		this.gid = gid;
		this.userName = userName;
	}

	public String getGid() {
		return this.gid;
	}

	public void setGid(String gid) {
		this.gid = gid;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblfavorisId))
			return false;
		TblfavorisId castOther = (TblfavorisId) other;

		return ((this.getGid() == castOther.getGid()) || (this.getGid() != null
				&& castOther.getGid() != null && this.getGid().equals(
				castOther.getGid())))
				&& ((this.getUserName() == castOther.getUserName()) || (this
						.getUserName() != null
						&& castOther.getUserName() != null && this
						.getUserName().equals(castOther.getUserName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGid() == null ? 0 : this.getGid().hashCode());
		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		return result;
	}

}
