package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * TblfieldId generated by hbm2java
 */
public class TblfieldId implements java.io.Serializable {

	private Integer id;
	private int ord;
	private Integer type;
	private int codeUser;
	private String graphId;
	private String vote;
	private String message;
	private Date voteDate;

	public TblfieldId() {
	}

	public TblfieldId(int ord, int codeUser, String vote, String message,
			Date voteDate) {
		this.ord = ord;
		this.codeUser = codeUser;
		this.vote = vote;
		this.message = message;
		this.voteDate = voteDate;
	}

	public TblfieldId(Integer id, int ord, Integer type, int codeUser,
			String graphId, String vote, String message, Date voteDate) {
		this.id = id;
		this.ord = ord;
		this.type = type;
		this.codeUser = codeUser;
		this.graphId = graphId;
		this.vote = vote;
		this.message = message;
		this.voteDate = voteDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getOrd() {
		return this.ord;
	}

	public void setOrd(int ord) {
		this.ord = ord;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public int getCodeUser() {
		return this.codeUser;
	}

	public void setCodeUser(int codeUser) {
		this.codeUser = codeUser;
	}

	public String getGraphId() {
		return this.graphId;
	}

	public void setGraphId(String graphId) {
		this.graphId = graphId;
	}

	public String getVote() {
		return this.vote;
	}

	public void setVote(String vote) {
		this.vote = vote;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getVoteDate() {
		return this.voteDate;
	}

	public void setVoteDate(Date voteDate) {
		this.voteDate = voteDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblfieldId))
			return false;
		TblfieldId castOther = (TblfieldId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& (this.getOrd() == castOther.getOrd())
				&& ((this.getType() == castOther.getType()) || (this.getType() != null
						&& castOther.getType() != null && this.getType()
						.equals(castOther.getType())))
				&& (this.getCodeUser() == castOther.getCodeUser())
				&& ((this.getGraphId() == castOther.getGraphId()) || (this
						.getGraphId() != null
						&& castOther.getGraphId() != null && this.getGraphId()
						.equals(castOther.getGraphId())))
				&& ((this.getVote() == castOther.getVote()) || (this.getVote() != null
						&& castOther.getVote() != null && this.getVote()
						.equals(castOther.getVote())))
				&& ((this.getMessage() == castOther.getMessage()) || (this
						.getMessage() != null
						&& castOther.getMessage() != null && this.getMessage()
						.equals(castOther.getMessage())))
				&& ((this.getVoteDate() == castOther.getVoteDate()) || (this
						.getVoteDate() != null
						&& castOther.getVoteDate() != null && this
						.getVoteDate().equals(castOther.getVoteDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + this.getOrd();
		result = 37 * result
				+ (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result + this.getCodeUser();
		result = 37 * result
				+ (getGraphId() == null ? 0 : this.getGraphId().hashCode());
		result = 37 * result
				+ (getVote() == null ? 0 : this.getVote().hashCode());
		result = 37 * result
				+ (getMessage() == null ? 0 : this.getMessage().hashCode());
		result = 37 * result
				+ (getVoteDate() == null ? 0 : this.getVoteDate().hashCode());
		return result;
	}

}
