package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Tblgraphs generated by hbm2java
 */
public class Tblgraphs implements java.io.Serializable {

	private String gid;
	private String gname;
	private String gref;
	private int glevel;
	private int gorientation;
	private String gtemplate;
	private Boolean gqgrCaptions;
	private Boolean gvisPublic;
	private String projectId;
	private Boolean gisOk;
	private String gversionNumber;
	private Integer gindice;
	private String gnews;
	private String gauthor;
	private Date gdesignDate;
	private Date gupdateDate;
	private String gverifNames;
	private String gapprobNames;
	private String glinkDoc;
	private String gobject;
	private String gdomain;
	private String gabrList;
	private String gdifList;
	private String gkeywords;
	private String gfield1;
	private String gfield2;
	private String gfield3;
	private Boolean gisModel;
	private Boolean ghtmlGen;
	private Boolean gdocGen;
	private Date gdifDate;
	private String icone;
	private String gtype;
	private Boolean gonlyLink;
	private Integer ggraphState;
	private String gbgcolor;
	private String gbgimagePath;

	public Tblgraphs() {
	}

	public Tblgraphs(String gid, String gname, String gref, int glevel,
			int gorientation, String projectId, Date gdesignDate,
			Date gupdateDate, Date gdifDate) {
		this.gid = gid;
		this.gname = gname;
		this.gref = gref;
		this.glevel = glevel;
		this.gorientation = gorientation;
		this.projectId = projectId;
		this.gdesignDate = gdesignDate;
		this.gupdateDate = gupdateDate;
		this.gdifDate = gdifDate;
	}

	public Tblgraphs(String gid, String gname, String gref, int glevel,
			int gorientation, String gtemplate, Boolean gqgrCaptions,
			Boolean gvisPublic, String projectId, Boolean gisOk,
			String gversionNumber, Integer gindice, String gnews,
			String gauthor, Date gdesignDate, Date gupdateDate,
			String gverifNames, String gapprobNames, String glinkDoc,
			String gobject, String gdomain, String gabrList, String gdifList,
			String gkeywords, String gfield1, String gfield2, String gfield3,
			Boolean gisModel, Boolean ghtmlGen, Boolean gdocGen, Date gdifDate,
			String icone, String gtype, Boolean gonlyLink, Integer ggraphState,
			String gbgcolor, String gbgimagePath) {
		this.gid = gid;
		this.gname = gname;
		this.gref = gref;
		this.glevel = glevel;
		this.gorientation = gorientation;
		this.gtemplate = gtemplate;
		this.gqgrCaptions = gqgrCaptions;
		this.gvisPublic = gvisPublic;
		this.projectId = projectId;
		this.gisOk = gisOk;
		this.gversionNumber = gversionNumber;
		this.gindice = gindice;
		this.gnews = gnews;
		this.gauthor = gauthor;
		this.gdesignDate = gdesignDate;
		this.gupdateDate = gupdateDate;
		this.gverifNames = gverifNames;
		this.gapprobNames = gapprobNames;
		this.glinkDoc = glinkDoc;
		this.gobject = gobject;
		this.gdomain = gdomain;
		this.gabrList = gabrList;
		this.gdifList = gdifList;
		this.gkeywords = gkeywords;
		this.gfield1 = gfield1;
		this.gfield2 = gfield2;
		this.gfield3 = gfield3;
		this.gisModel = gisModel;
		this.ghtmlGen = ghtmlGen;
		this.gdocGen = gdocGen;
		this.gdifDate = gdifDate;
		this.icone = icone;
		this.gtype = gtype;
		this.gonlyLink = gonlyLink;
		this.ggraphState = ggraphState;
		this.gbgcolor = gbgcolor;
		this.gbgimagePath = gbgimagePath;
	}

	public String getGid() {
		return this.gid;
	}

	public void setGid(String gid) {
		this.gid = gid;
	}

	public String getGname() {
		return this.gname;
	}

	public void setGname(String gname) {
		this.gname = gname;
	}

	public String getGref() {
		return this.gref;
	}

	public void setGref(String gref) {
		this.gref = gref;
	}

	public int getGlevel() {
		return this.glevel;
	}

	public void setGlevel(int glevel) {
		this.glevel = glevel;
	}

	public int getGorientation() {
		return this.gorientation;
	}

	public void setGorientation(int gorientation) {
		this.gorientation = gorientation;
	}

	public String getGtemplate() {
		return this.gtemplate;
	}

	public void setGtemplate(String gtemplate) {
		this.gtemplate = gtemplate;
	}

	public Boolean getGqgrCaptions() {
		return this.gqgrCaptions;
	}

	public void setGqgrCaptions(Boolean gqgrCaptions) {
		this.gqgrCaptions = gqgrCaptions;
	}

	public Boolean getGvisPublic() {
		return this.gvisPublic;
	}

	public void setGvisPublic(Boolean gvisPublic) {
		this.gvisPublic = gvisPublic;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public Boolean getGisOk() {
		return this.gisOk;
	}

	public void setGisOk(Boolean gisOk) {
		this.gisOk = gisOk;
	}

	public String getGversionNumber() {
		return this.gversionNumber;
	}

	public void setGversionNumber(String gversionNumber) {
		this.gversionNumber = gversionNumber;
	}

	public Integer getGindice() {
		return this.gindice;
	}

	public void setGindice(Integer gindice) {
		this.gindice = gindice;
	}

	public String getGnews() {
		return this.gnews;
	}

	public void setGnews(String gnews) {
		this.gnews = gnews;
	}

	public String getGauthor() {
		return this.gauthor;
	}

	public void setGauthor(String gauthor) {
		this.gauthor = gauthor;
	}

	public Date getGdesignDate() {
		return this.gdesignDate;
	}

	public void setGdesignDate(Date gdesignDate) {
		this.gdesignDate = gdesignDate;
	}

	public Date getGupdateDate() {
		return this.gupdateDate;
	}

	public void setGupdateDate(Date gupdateDate) {
		this.gupdateDate = gupdateDate;
	}

	public String getGverifNames() {
		return this.gverifNames;
	}

	public void setGverifNames(String gverifNames) {
		this.gverifNames = gverifNames;
	}

	public String getGapprobNames() {
		return this.gapprobNames;
	}

	public void setGapprobNames(String gapprobNames) {
		this.gapprobNames = gapprobNames;
	}

	public String getGlinkDoc() {
		return this.glinkDoc;
	}

	public void setGlinkDoc(String glinkDoc) {
		this.glinkDoc = glinkDoc;
	}

	public String getGobject() {
		return this.gobject;
	}

	public void setGobject(String gobject) {
		this.gobject = gobject;
	}

	public String getGdomain() {
		return this.gdomain;
	}

	public void setGdomain(String gdomain) {
		this.gdomain = gdomain;
	}

	public String getGabrList() {
		return this.gabrList;
	}

	public void setGabrList(String gabrList) {
		this.gabrList = gabrList;
	}

	public String getGdifList() {
		return this.gdifList;
	}

	public void setGdifList(String gdifList) {
		this.gdifList = gdifList;
	}

	public String getGkeywords() {
		return this.gkeywords;
	}

	public void setGkeywords(String gkeywords) {
		this.gkeywords = gkeywords;
	}

	public String getGfield1() {
		return this.gfield1;
	}

	public void setGfield1(String gfield1) {
		this.gfield1 = gfield1;
	}

	public String getGfield2() {
		return this.gfield2;
	}

	public void setGfield2(String gfield2) {
		this.gfield2 = gfield2;
	}

	public String getGfield3() {
		return this.gfield3;
	}

	public void setGfield3(String gfield3) {
		this.gfield3 = gfield3;
	}

	public Boolean getGisModel() {
		return this.gisModel;
	}

	public void setGisModel(Boolean gisModel) {
		this.gisModel = gisModel;
	}

	public Boolean getGhtmlGen() {
		return this.ghtmlGen;
	}

	public void setGhtmlGen(Boolean ghtmlGen) {
		this.ghtmlGen = ghtmlGen;
	}

	public Boolean getGdocGen() {
		return this.gdocGen;
	}

	public void setGdocGen(Boolean gdocGen) {
		this.gdocGen = gdocGen;
	}

	public Date getGdifDate() {
		return this.gdifDate;
	}

	public void setGdifDate(Date gdifDate) {
		this.gdifDate = gdifDate;
	}

	public String getIcone() {
		return this.icone;
	}

	public void setIcone(String icone) {
		this.icone = icone;
	}

	public String getGtype() {
		return this.gtype;
	}

	public void setGtype(String gtype) {
		this.gtype = gtype;
	}

	public Boolean getGonlyLink() {
		return this.gonlyLink;
	}

	public void setGonlyLink(Boolean gonlyLink) {
		this.gonlyLink = gonlyLink;
	}

	public Integer getGgraphState() {
		return this.ggraphState;
	}

	public void setGgraphState(Integer ggraphState) {
		this.ggraphState = ggraphState;
	}

	public String getGbgcolor() {
		return this.gbgcolor;
	}

	public void setGbgcolor(String gbgcolor) {
		this.gbgcolor = gbgcolor;
	}

	public String getGbgimagePath() {
		return this.gbgimagePath;
	}

	public void setGbgimagePath(String gbgimagePath) {
		this.gbgimagePath = gbgimagePath;
	}

}
