package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * TblgroupsId generated by hbm2java
 */
public class TblgroupsId implements java.io.Serializable {

	private Integer groupSid;
	private Integer accountSid;

	public TblgroupsId() {
	}

	public TblgroupsId(Integer groupSid, Integer accountSid) {
		this.groupSid = groupSid;
		this.accountSid = accountSid;
	}

	public Integer getGroupSid() {
		return this.groupSid;
	}

	public void setGroupSid(Integer groupSid) {
		this.groupSid = groupSid;
	}

	public Integer getAccountSid() {
		return this.accountSid;
	}

	public void setAccountSid(Integer accountSid) {
		this.accountSid = accountSid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblgroupsId))
			return false;
		TblgroupsId castOther = (TblgroupsId) other;

		return ((this.getGroupSid() == castOther.getGroupSid()) || (this
				.getGroupSid() != null
				&& castOther.getGroupSid() != null && this.getGroupSid()
				.equals(castOther.getGroupSid())))
				&& ((this.getAccountSid() == castOther.getAccountSid()) || (this
						.getAccountSid() != null
						&& castOther.getAccountSid() != null && this
						.getAccountSid().equals(castOther.getAccountSid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGroupSid() == null ? 0 : this.getGroupSid().hashCode());
		result = 37
				* result
				+ (getAccountSid() == null ? 0 : this.getAccountSid()
						.hashCode());
		return result;
	}

}
