package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblgroups generated by hbm2java
 */
public class Tblgroups implements java.io.Serializable {

	private TblgroupsId id;

	public Tblgroups() {
	}

	public Tblgroups(TblgroupsId id) {
		this.id = id;
	}

	public TblgroupsId getId() {
		return this.id;
	}

	public void setId(TblgroupsId id) {
		this.id = id;
	}

}
