package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblindic generated by hbm2java
 */
public class Tblindic implements java.io.Serializable {

	private Integer iidx;
	private String iid;
	private String iref;
	private String iname;
	private String idescription;
	private String icalcul;
	private String iperiode;
	private int itype;
	private float iobjectif;
	private int iponderation;
	private float iactualValue;
	private int itrend;
	private int inbVal;
	private String iresponsable;
	private int inbDec;
	private float iscaleMin;
	private float iscaleMax;
	private int ibsbtype;
	private int idbitemId;

	public Tblindic() {
	}

	public Tblindic(String iref, String iname, String idescription,
			String icalcul, String iperiode, int itype, float iobjectif,
			int iponderation, float iactualValue, int itrend, int inbVal,
			String iresponsable, int inbDec, float iscaleMin, float iscaleMax,
			int ibsbtype, int idbitemId) {
		this.iref = iref;
		this.iname = iname;
		this.idescription = idescription;
		this.icalcul = icalcul;
		this.iperiode = iperiode;
		this.itype = itype;
		this.iobjectif = iobjectif;
		this.iponderation = iponderation;
		this.iactualValue = iactualValue;
		this.itrend = itrend;
		this.inbVal = inbVal;
		this.iresponsable = iresponsable;
		this.inbDec = inbDec;
		this.iscaleMin = iscaleMin;
		this.iscaleMax = iscaleMax;
		this.ibsbtype = ibsbtype;
		this.idbitemId = idbitemId;
	}

	public Tblindic(String iid, String iref, String iname, String idescription,
			String icalcul, String iperiode, int itype, float iobjectif,
			int iponderation, float iactualValue, int itrend, int inbVal,
			String iresponsable, int inbDec, float iscaleMin, float iscaleMax,
			int ibsbtype, int idbitemId) {
		this.iid = iid;
		this.iref = iref;
		this.iname = iname;
		this.idescription = idescription;
		this.icalcul = icalcul;
		this.iperiode = iperiode;
		this.itype = itype;
		this.iobjectif = iobjectif;
		this.iponderation = iponderation;
		this.iactualValue = iactualValue;
		this.itrend = itrend;
		this.inbVal = inbVal;
		this.iresponsable = iresponsable;
		this.inbDec = inbDec;
		this.iscaleMin = iscaleMin;
		this.iscaleMax = iscaleMax;
		this.ibsbtype = ibsbtype;
		this.idbitemId = idbitemId;
	}

	public Integer getIidx() {
		return this.iidx;
	}

	public void setIidx(Integer iidx) {
		this.iidx = iidx;
	}

	public String getIid() {
		return this.iid;
	}

	public void setIid(String iid) {
		this.iid = iid;
	}

	public String getIref() {
		return this.iref;
	}

	public void setIref(String iref) {
		this.iref = iref;
	}

	public String getIname() {
		return this.iname;
	}

	public void setIname(String iname) {
		this.iname = iname;
	}

	public String getIdescription() {
		return this.idescription;
	}

	public void setIdescription(String idescription) {
		this.idescription = idescription;
	}

	public String getIcalcul() {
		return this.icalcul;
	}

	public void setIcalcul(String icalcul) {
		this.icalcul = icalcul;
	}

	public String getIperiode() {
		return this.iperiode;
	}

	public void setIperiode(String iperiode) {
		this.iperiode = iperiode;
	}

	public int getItype() {
		return this.itype;
	}

	public void setItype(int itype) {
		this.itype = itype;
	}

	public float getIobjectif() {
		return this.iobjectif;
	}

	public void setIobjectif(float iobjectif) {
		this.iobjectif = iobjectif;
	}

	public int getIponderation() {
		return this.iponderation;
	}

	public void setIponderation(int iponderation) {
		this.iponderation = iponderation;
	}

	public float getIactualValue() {
		return this.iactualValue;
	}

	public void setIactualValue(float iactualValue) {
		this.iactualValue = iactualValue;
	}

	public int getItrend() {
		return this.itrend;
	}

	public void setItrend(int itrend) {
		this.itrend = itrend;
	}

	public int getInbVal() {
		return this.inbVal;
	}

	public void setInbVal(int inbVal) {
		this.inbVal = inbVal;
	}

	public String getIresponsable() {
		return this.iresponsable;
	}

	public void setIresponsable(String iresponsable) {
		this.iresponsable = iresponsable;
	}

	public int getInbDec() {
		return this.inbDec;
	}

	public void setInbDec(int inbDec) {
		this.inbDec = inbDec;
	}

	public float getIscaleMin() {
		return this.iscaleMin;
	}

	public void setIscaleMin(float iscaleMin) {
		this.iscaleMin = iscaleMin;
	}

	public float getIscaleMax() {
		return this.iscaleMax;
	}

	public void setIscaleMax(float iscaleMax) {
		this.iscaleMax = iscaleMax;
	}

	public int getIbsbtype() {
		return this.ibsbtype;
	}

	public void setIbsbtype(int ibsbtype) {
		this.ibsbtype = ibsbtype;
	}

	public int getIdbitemId() {
		return this.idbitemId;
	}

	public void setIdbitemId(int idbitemId) {
		this.idbitemId = idbitemId;
	}

}
