package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblindval generated by hbm2java
 */
public class Tblindval implements java.io.Serializable {

	private TblindvalId id;

	public Tblindval() {
	}

	public Tblindval(TblindvalId id) {
		this.id = id;
	}

	public TblindvalId getId() {
		return this.id;
	}

	public void setId(TblindvalId id) {
		this.id = id;
	}

}
