package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tbllogs generated by hbm2java
 */
public class Tbllogs implements java.io.Serializable {

	private TbllogsId id;

	public Tbllogs() {
	}

	public Tbllogs(TbllogsId id) {
		this.id = id;
	}

	public TbllogsId getId() {
		return this.id;
	}

	public void setId(TbllogsId id) {
		this.id = id;
	}

}
