package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * TblnumshapesId generated by hbm2java
 */
public class TblnumshapesId implements java.io.Serializable {

	private Integer nsId;
	private String nsGraphId;
	private int nsTypeId;
	private int nsFormat;
	private Boolean nsChrono;
	private Boolean nsAllTypes;
	private Boolean nsSameFormat;

	public TblnumshapesId() {
	}

	public TblnumshapesId(String nsGraphId, int nsTypeId, int nsFormat) {
		this.nsGraphId = nsGraphId;
		this.nsTypeId = nsTypeId;
		this.nsFormat = nsFormat;
	}

	public TblnumshapesId(Integer nsId, String nsGraphId, int nsTypeId,
			int nsFormat, Boolean nsChrono, Boolean nsAllTypes,
			Boolean nsSameFormat) {
		this.nsId = nsId;
		this.nsGraphId = nsGraphId;
		this.nsTypeId = nsTypeId;
		this.nsFormat = nsFormat;
		this.nsChrono = nsChrono;
		this.nsAllTypes = nsAllTypes;
		this.nsSameFormat = nsSameFormat;
	}

	public Integer getNsId() {
		return this.nsId;
	}

	public void setNsId(Integer nsId) {
		this.nsId = nsId;
	}

	public String getNsGraphId() {
		return this.nsGraphId;
	}

	public void setNsGraphId(String nsGraphId) {
		this.nsGraphId = nsGraphId;
	}

	public int getNsTypeId() {
		return this.nsTypeId;
	}

	public void setNsTypeId(int nsTypeId) {
		this.nsTypeId = nsTypeId;
	}

	public int getNsFormat() {
		return this.nsFormat;
	}

	public void setNsFormat(int nsFormat) {
		this.nsFormat = nsFormat;
	}

	public Boolean getNsChrono() {
		return this.nsChrono;
	}

	public void setNsChrono(Boolean nsChrono) {
		this.nsChrono = nsChrono;
	}

	public Boolean getNsAllTypes() {
		return this.nsAllTypes;
	}

	public void setNsAllTypes(Boolean nsAllTypes) {
		this.nsAllTypes = nsAllTypes;
	}

	public Boolean getNsSameFormat() {
		return this.nsSameFormat;
	}

	public void setNsSameFormat(Boolean nsSameFormat) {
		this.nsSameFormat = nsSameFormat;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblnumshapesId))
			return false;
		TblnumshapesId castOther = (TblnumshapesId) other;

		return ((this.getNsId() == castOther.getNsId()) || (this.getNsId() != null
				&& castOther.getNsId() != null && this.getNsId().equals(
				castOther.getNsId())))
				&& ((this.getNsGraphId() == castOther.getNsGraphId()) || (this
						.getNsGraphId() != null
						&& castOther.getNsGraphId() != null && this
						.getNsGraphId().equals(castOther.getNsGraphId())))
				&& (this.getNsTypeId() == castOther.getNsTypeId())
				&& (this.getNsFormat() == castOther.getNsFormat())
				&& ((this.getNsChrono() == castOther.getNsChrono()) || (this
						.getNsChrono() != null
						&& castOther.getNsChrono() != null && this
						.getNsChrono().equals(castOther.getNsChrono())))
				&& ((this.getNsAllTypes() == castOther.getNsAllTypes()) || (this
						.getNsAllTypes() != null
						&& castOther.getNsAllTypes() != null && this
						.getNsAllTypes().equals(castOther.getNsAllTypes())))
				&& ((this.getNsSameFormat() == castOther.getNsSameFormat()) || (this
						.getNsSameFormat() != null
						&& castOther.getNsSameFormat() != null && this
						.getNsSameFormat().equals(castOther.getNsSameFormat())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNsId() == null ? 0 : this.getNsId().hashCode());
		result = 37 * result
				+ (getNsGraphId() == null ? 0 : this.getNsGraphId().hashCode());
		result = 37 * result + this.getNsTypeId();
		result = 37 * result + this.getNsFormat();
		result = 37 * result
				+ (getNsChrono() == null ? 0 : this.getNsChrono().hashCode());
		result = 37
				* result
				+ (getNsAllTypes() == null ? 0 : this.getNsAllTypes()
						.hashCode());
		result = 37
				* result
				+ (getNsSameFormat() == null ? 0 : this.getNsSameFormat()
						.hashCode());
		return result;
	}

}
