package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblnumshapes generated by hbm2java
 */
public class Tblnumshapes implements java.io.Serializable {

	private TblnumshapesId id;

	public Tblnumshapes() {
	}

	public Tblnumshapes(TblnumshapesId id) {
		this.id = id;
	}

	public TblnumshapesId getId() {
		return this.id;
	}

	public void setId(TblnumshapesId id) {
		this.id = id;
	}

}
