package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tbloptions generated by hbm2java
 */
public class Tbloptions implements java.io.Serializable {

	private TbloptionsId id;

	public Tbloptions() {
	}

	public Tbloptions(TbloptionsId id) {
		this.id = id;
	}

	public TbloptionsId getId() {
		return this.id;
	}

	public void setId(TbloptionsId id) {
		this.id = id;
	}

}
