package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblpropvalues generated by hbm2java
 */
public class Tblpropvalues implements java.io.Serializable {

	private TblpropvaluesId id;

	public Tblpropvalues() {
	}

	public Tblpropvalues(TblpropvaluesId id) {
		this.id = id;
	}

	public TblpropvaluesId getId() {
		return this.id;
	}

	public void setId(TblpropvaluesId id) {
		this.id = id;
	}

}
