package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblpossiblevalues generated by hbm2java
 */
public class Tblpossiblevalues implements java.io.Serializable {

	private TblpossiblevaluesId id;

	public Tblpossiblevalues() {
	}

	public Tblpossiblevalues(TblpossiblevaluesId id) {
		this.id = id;
	}

	public TblpossiblevaluesId getId() {
		return this.id;
	}

	public void setId(TblpossiblevaluesId id) {
		this.id = id;
	}

}
