package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Tblprojects generated by hbm2java
 */
public class Tblprojects implements java.io.Serializable {

	private Integer idx;
	private String projectId;
	private String projectName;
	private Boolean visPublic;
	private String parentId;
	private Date createDate;
	private String icone;
	private String responsable;
	private Boolean applyRestr;
	private String pref;
	private String pobject;
	private String pdomain;
	private Integer fldLevel;
	private Integer fldNumber;

	public Tblprojects() {
	}

	public Tblprojects(String projectName, Date createDate) {
		this.projectName = projectName;
		this.createDate = createDate;
	}

	public Tblprojects(String projectId, String projectName, Boolean visPublic,
			String parentId, Date createDate, String icone, String responsable,
			Boolean applyRestr, String pref, String pobject, String pdomain,
			Integer fldLevel, Integer fldNumber) {
		this.projectId = projectId;
		this.projectName = projectName;
		this.visPublic = visPublic;
		this.parentId = parentId;
		this.createDate = createDate;
		this.icone = icone;
		this.responsable = responsable;
		this.applyRestr = applyRestr;
		this.pref = pref;
		this.pobject = pobject;
		this.pdomain = pdomain;
		this.fldLevel = fldLevel;
		this.fldNumber = fldNumber;
	}

	public Integer getIdx() {
		return this.idx;
	}

	public void setIdx(Integer idx) {
		this.idx = idx;
	}

	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public Boolean getVisPublic() {
		return this.visPublic;
	}

	public void setVisPublic(Boolean visPublic) {
		this.visPublic = visPublic;
	}

	public String getParentId() {
		return this.parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getIcone() {
		return this.icone;
	}

	public void setIcone(String icone) {
		this.icone = icone;
	}

	public String getResponsable() {
		return this.responsable;
	}

	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}

	public Boolean getApplyRestr() {
		return this.applyRestr;
	}

	public void setApplyRestr(Boolean applyRestr) {
		this.applyRestr = applyRestr;
	}

	public String getPref() {
		return this.pref;
	}

	public void setPref(String pref) {
		this.pref = pref;
	}

	public String getPobject() {
		return this.pobject;
	}

	public void setPobject(String pobject) {
		this.pobject = pobject;
	}

	public String getPdomain() {
		return this.pdomain;
	}

	public void setPdomain(String pdomain) {
		this.pdomain = pdomain;
	}

	public Integer getFldLevel() {
		return this.fldLevel;
	}

	public void setFldLevel(Integer fldLevel) {
		this.fldLevel = fldLevel;
	}

	public Integer getFldNumber() {
		return this.fldNumber;
	}

	public void setFldNumber(Integer fldNumber) {
		this.fldNumber = fldNumber;
	}

}
