package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblproperties generated by hbm2java
 */
public class Tblproperties implements java.io.Serializable {

	private TblpropertiesId id;

	public Tblproperties() {
	}

	public Tblproperties(TblpropertiesId id) {
		this.id = id;
	}

	public TblpropertiesId getId() {
		return this.id;
	}

	public void setId(TblpropertiesId id) {
		this.id = id;
	}

}
