package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * TblpropertiesId generated by hbm2java
 */
public class TblpropertiesId implements java.io.Serializable {

	private String pvCode;
	private String pvDescription;
	private short pvType;
	private Boolean pvGraphUse;
	private Boolean pvDocUse;
	private Boolean pvEntityUse;
	private Boolean pvFormUse;
	private Boolean pvActorUse;
	private Boolean pvFolderUse;
	private int pvOrder;
	private String pvLongDescription;
	private Boolean pvIndicatorUse;
	private int pvUseDetail;

	public TblpropertiesId() {
	}

	public TblpropertiesId(String pvDescription, short pvType, int pvOrder,
			String pvLongDescription, int pvUseDetail) {
		this.pvDescription = pvDescription;
		this.pvType = pvType;
		this.pvOrder = pvOrder;
		this.pvLongDescription = pvLongDescription;
		this.pvUseDetail = pvUseDetail;
	}

	public TblpropertiesId(String pvCode, String pvDescription, short pvType,
			Boolean pvGraphUse, Boolean pvDocUse, Boolean pvEntityUse,
			Boolean pvFormUse, Boolean pvActorUse, Boolean pvFolderUse,
			int pvOrder, String pvLongDescription, Boolean pvIndicatorUse,
			int pvUseDetail) {
		this.pvCode = pvCode;
		this.pvDescription = pvDescription;
		this.pvType = pvType;
		this.pvGraphUse = pvGraphUse;
		this.pvDocUse = pvDocUse;
		this.pvEntityUse = pvEntityUse;
		this.pvFormUse = pvFormUse;
		this.pvActorUse = pvActorUse;
		this.pvFolderUse = pvFolderUse;
		this.pvOrder = pvOrder;
		this.pvLongDescription = pvLongDescription;
		this.pvIndicatorUse = pvIndicatorUse;
		this.pvUseDetail = pvUseDetail;
	}

	public String getPvCode() {
		return this.pvCode;
	}

	public void setPvCode(String pvCode) {
		this.pvCode = pvCode;
	}

	public String getPvDescription() {
		return this.pvDescription;
	}

	public void setPvDescription(String pvDescription) {
		this.pvDescription = pvDescription;
	}

	public short getPvType() {
		return this.pvType;
	}

	public void setPvType(short pvType) {
		this.pvType = pvType;
	}

	public Boolean getPvGraphUse() {
		return this.pvGraphUse;
	}

	public void setPvGraphUse(Boolean pvGraphUse) {
		this.pvGraphUse = pvGraphUse;
	}

	public Boolean getPvDocUse() {
		return this.pvDocUse;
	}

	public void setPvDocUse(Boolean pvDocUse) {
		this.pvDocUse = pvDocUse;
	}

	public Boolean getPvEntityUse() {
		return this.pvEntityUse;
	}

	public void setPvEntityUse(Boolean pvEntityUse) {
		this.pvEntityUse = pvEntityUse;
	}

	public Boolean getPvFormUse() {
		return this.pvFormUse;
	}

	public void setPvFormUse(Boolean pvFormUse) {
		this.pvFormUse = pvFormUse;
	}

	public Boolean getPvActorUse() {
		return this.pvActorUse;
	}

	public void setPvActorUse(Boolean pvActorUse) {
		this.pvActorUse = pvActorUse;
	}

	public Boolean getPvFolderUse() {
		return this.pvFolderUse;
	}

	public void setPvFolderUse(Boolean pvFolderUse) {
		this.pvFolderUse = pvFolderUse;
	}

	public int getPvOrder() {
		return this.pvOrder;
	}

	public void setPvOrder(int pvOrder) {
		this.pvOrder = pvOrder;
	}

	public String getPvLongDescription() {
		return this.pvLongDescription;
	}

	public void setPvLongDescription(String pvLongDescription) {
		this.pvLongDescription = pvLongDescription;
	}

	public Boolean getPvIndicatorUse() {
		return this.pvIndicatorUse;
	}

	public void setPvIndicatorUse(Boolean pvIndicatorUse) {
		this.pvIndicatorUse = pvIndicatorUse;
	}

	public int getPvUseDetail() {
		return this.pvUseDetail;
	}

	public void setPvUseDetail(int pvUseDetail) {
		this.pvUseDetail = pvUseDetail;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblpropertiesId))
			return false;
		TblpropertiesId castOther = (TblpropertiesId) other;

		return ((this.getPvCode() == castOther.getPvCode()) || (this
				.getPvCode() != null
				&& castOther.getPvCode() != null && this.getPvCode().equals(
				castOther.getPvCode())))
				&& ((this.getPvDescription() == castOther.getPvDescription()) || (this
						.getPvDescription() != null
						&& castOther.getPvDescription() != null && this
						.getPvDescription()
						.equals(castOther.getPvDescription())))
				&& (this.getPvType() == castOther.getPvType())
				&& ((this.getPvGraphUse() == castOther.getPvGraphUse()) || (this
						.getPvGraphUse() != null
						&& castOther.getPvGraphUse() != null && this
						.getPvGraphUse().equals(castOther.getPvGraphUse())))
				&& ((this.getPvDocUse() == castOther.getPvDocUse()) || (this
						.getPvDocUse() != null
						&& castOther.getPvDocUse() != null && this
						.getPvDocUse().equals(castOther.getPvDocUse())))
				&& ((this.getPvEntityUse() == castOther.getPvEntityUse()) || (this
						.getPvEntityUse() != null
						&& castOther.getPvEntityUse() != null && this
						.getPvEntityUse().equals(castOther.getPvEntityUse())))
				&& ((this.getPvFormUse() == castOther.getPvFormUse()) || (this
						.getPvFormUse() != null
						&& castOther.getPvFormUse() != null && this
						.getPvFormUse().equals(castOther.getPvFormUse())))
				&& ((this.getPvActorUse() == castOther.getPvActorUse()) || (this
						.getPvActorUse() != null
						&& castOther.getPvActorUse() != null && this
						.getPvActorUse().equals(castOther.getPvActorUse())))
				&& ((this.getPvFolderUse() == castOther.getPvFolderUse()) || (this
						.getPvFolderUse() != null
						&& castOther.getPvFolderUse() != null && this
						.getPvFolderUse().equals(castOther.getPvFolderUse())))
				&& (this.getPvOrder() == castOther.getPvOrder())
				&& ((this.getPvLongDescription() == castOther
						.getPvLongDescription()) || (this
						.getPvLongDescription() != null
						&& castOther.getPvLongDescription() != null && this
						.getPvLongDescription().equals(
								castOther.getPvLongDescription())))
				&& ((this.getPvIndicatorUse() == castOther.getPvIndicatorUse()) || (this
						.getPvIndicatorUse() != null
						&& castOther.getPvIndicatorUse() != null && this
						.getPvIndicatorUse().equals(
								castOther.getPvIndicatorUse())))
				&& (this.getPvUseDetail() == castOther.getPvUseDetail());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPvCode() == null ? 0 : this.getPvCode().hashCode());
		result = 37
				* result
				+ (getPvDescription() == null ? 0 : this.getPvDescription()
						.hashCode());
		result = 37 * result + this.getPvType();
		result = 37
				* result
				+ (getPvGraphUse() == null ? 0 : this.getPvGraphUse()
						.hashCode());
		result = 37 * result
				+ (getPvDocUse() == null ? 0 : this.getPvDocUse().hashCode());
		result = 37
				* result
				+ (getPvEntityUse() == null ? 0 : this.getPvEntityUse()
						.hashCode());
		result = 37 * result
				+ (getPvFormUse() == null ? 0 : this.getPvFormUse().hashCode());
		result = 37
				* result
				+ (getPvActorUse() == null ? 0 : this.getPvActorUse()
						.hashCode());
		result = 37
				* result
				+ (getPvFolderUse() == null ? 0 : this.getPvFolderUse()
						.hashCode());
		result = 37 * result + this.getPvOrder();
		result = 37
				* result
				+ (getPvLongDescription() == null ? 0 : this
						.getPvLongDescription().hashCode());
		result = 37
				* result
				+ (getPvIndicatorUse() == null ? 0 : this.getPvIndicatorUse()
						.hashCode());
		result = 37 * result + this.getPvUseDetail();
		return result;
	}

}
