package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblqgrfunctions generated by hbm2java
 */
public class Tblqgrfunctions implements java.io.Serializable {

	private TblqgrfunctionsId id;

	public Tblqgrfunctions() {
	}

	public Tblqgrfunctions(TblqgrfunctionsId id) {
		this.id = id;
	}

	public TblqgrfunctionsId getId() {
		return this.id;
	}

	public void setId(TblqgrfunctionsId id) {
		this.id = id;
	}

}
