package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * TblrighttypesId generated by hbm2java
 */
public class TblrighttypesId implements java.io.Serializable {

	private Integer rtypeId;
	private String rtypeDescription;
	private int rtypeOfice;

	public TblrighttypesId() {
	}

	public TblrighttypesId(String rtypeDescription, int rtypeOfice) {
		this.rtypeDescription = rtypeDescription;
		this.rtypeOfice = rtypeOfice;
	}

	public TblrighttypesId(Integer rtypeId, String rtypeDescription,
			int rtypeOfice) {
		this.rtypeId = rtypeId;
		this.rtypeDescription = rtypeDescription;
		this.rtypeOfice = rtypeOfice;
	}

	public Integer getRtypeId() {
		return this.rtypeId;
	}

	public void setRtypeId(Integer rtypeId) {
		this.rtypeId = rtypeId;
	}

	public String getRtypeDescription() {
		return this.rtypeDescription;
	}

	public void setRtypeDescription(String rtypeDescription) {
		this.rtypeDescription = rtypeDescription;
	}

	public int getRtypeOfice() {
		return this.rtypeOfice;
	}

	public void setRtypeOfice(int rtypeOfice) {
		this.rtypeOfice = rtypeOfice;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblrighttypesId))
			return false;
		TblrighttypesId castOther = (TblrighttypesId) other;

		return ((this.getRtypeId() == castOther.getRtypeId()) || (this
				.getRtypeId() != null
				&& castOther.getRtypeId() != null && this.getRtypeId().equals(
				castOther.getRtypeId())))
				&& ((this.getRtypeDescription() == castOther
						.getRtypeDescription()) || (this.getRtypeDescription() != null
						&& castOther.getRtypeDescription() != null && this
						.getRtypeDescription().equals(
								castOther.getRtypeDescription())))
				&& (this.getRtypeOfice() == castOther.getRtypeOfice());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRtypeId() == null ? 0 : this.getRtypeId().hashCode());
		result = 37
				* result
				+ (getRtypeDescription() == null ? 0 : this
						.getRtypeDescription().hashCode());
		result = 37 * result + this.getRtypeOfice();
		return result;
	}

}
