package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblrighttypes generated by hbm2java
 */
public class Tblrighttypes implements java.io.Serializable {

	private TblrighttypesId id;

	public Tblrighttypes() {
	}

	public Tblrighttypes(TblrighttypesId id) {
		this.id = id;
	}

	public TblrighttypesId getId() {
		return this.id;
	}

	public void setId(TblrighttypesId id) {
		this.id = id;
	}

}
