package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblrightsaccess generated by hbm2java
 */
public class Tblrightsaccess implements java.io.Serializable {

	private TblrightsaccessId id;

	public Tblrightsaccess() {
	}

	public Tblrightsaccess(TblrightsaccessId id) {
		this.id = id;
	}

	public TblrightsaccessId getId() {
		return this.id;
	}

	public void setId(TblrightsaccessId id) {
		this.id = id;
	}

}
