package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * TblrightsaccessId generated by hbm2java
 */
public class TblrightsaccessId implements java.io.Serializable {

	private String raUserName;
	private String raObjectId;
	private int raObjectType;
	private Integer raAccessId;
	private int raRightType;

	public TblrightsaccessId() {
	}

	public TblrightsaccessId(String raUserName, String raObjectId,
			int raObjectType, int raRightType) {
		this.raUserName = raUserName;
		this.raObjectId = raObjectId;
		this.raObjectType = raObjectType;
		this.raRightType = raRightType;
	}

	public TblrightsaccessId(String raUserName, String raObjectId,
			int raObjectType, Integer raAccessId, int raRightType) {
		this.raUserName = raUserName;
		this.raObjectId = raObjectId;
		this.raObjectType = raObjectType;
		this.raAccessId = raAccessId;
		this.raRightType = raRightType;
	}

	public String getRaUserName() {
		return this.raUserName;
	}

	public void setRaUserName(String raUserName) {
		this.raUserName = raUserName;
	}

	public String getRaObjectId() {
		return this.raObjectId;
	}

	public void setRaObjectId(String raObjectId) {
		this.raObjectId = raObjectId;
	}

	public int getRaObjectType() {
		return this.raObjectType;
	}

	public void setRaObjectType(int raObjectType) {
		this.raObjectType = raObjectType;
	}

	public Integer getRaAccessId() {
		return this.raAccessId;
	}

	public void setRaAccessId(Integer raAccessId) {
		this.raAccessId = raAccessId;
	}

	public int getRaRightType() {
		return this.raRightType;
	}

	public void setRaRightType(int raRightType) {
		this.raRightType = raRightType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblrightsaccessId))
			return false;
		TblrightsaccessId castOther = (TblrightsaccessId) other;

		return ((this.getRaUserName() == castOther.getRaUserName()) || (this
				.getRaUserName() != null
				&& castOther.getRaUserName() != null && this.getRaUserName()
				.equals(castOther.getRaUserName())))
				&& ((this.getRaObjectId() == castOther.getRaObjectId()) || (this
						.getRaObjectId() != null
						&& castOther.getRaObjectId() != null && this
						.getRaObjectId().equals(castOther.getRaObjectId())))
				&& (this.getRaObjectType() == castOther.getRaObjectType())
				&& ((this.getRaAccessId() == castOther.getRaAccessId()) || (this
						.getRaAccessId() != null
						&& castOther.getRaAccessId() != null && this
						.getRaAccessId().equals(castOther.getRaAccessId())))
				&& (this.getRaRightType() == castOther.getRaRightType());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getRaUserName() == null ? 0 : this.getRaUserName()
						.hashCode());
		result = 37
				* result
				+ (getRaObjectId() == null ? 0 : this.getRaObjectId()
						.hashCode());
		result = 37 * result + this.getRaObjectType();
		result = 37
				* result
				+ (getRaAccessId() == null ? 0 : this.getRaAccessId()
						.hashCode());
		result = 37 * result + this.getRaRightType();
		return result;
	}

}
