package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * TblshapesId generated by hbm2java
 */
public class TblshapesId implements java.io.Serializable {

	private String shGraphId;
	private String shFormId;
	private int shTypeId;
	private String shName;
	private String shNumber;

	public TblshapesId() {
	}

	public TblshapesId(int shTypeId, String shName, String shNumber) {
		this.shTypeId = shTypeId;
		this.shName = shName;
		this.shNumber = shNumber;
	}

	public TblshapesId(String shGraphId, String shFormId, int shTypeId,
			String shName, String shNumber) {
		this.shGraphId = shGraphId;
		this.shFormId = shFormId;
		this.shTypeId = shTypeId;
		this.shName = shName;
		this.shNumber = shNumber;
	}

	public String getShGraphId() {
		return this.shGraphId;
	}

	public void setShGraphId(String shGraphId) {
		this.shGraphId = shGraphId;
	}

	public String getShFormId() {
		return this.shFormId;
	}

	public void setShFormId(String shFormId) {
		this.shFormId = shFormId;
	}

	public int getShTypeId() {
		return this.shTypeId;
	}

	public void setShTypeId(int shTypeId) {
		this.shTypeId = shTypeId;
	}

	public String getShName() {
		return this.shName;
	}

	public void setShName(String shName) {
		this.shName = shName;
	}

	public String getShNumber() {
		return this.shNumber;
	}

	public void setShNumber(String shNumber) {
		this.shNumber = shNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblshapesId))
			return false;
		TblshapesId castOther = (TblshapesId) other;

		return ((this.getShGraphId() == castOther.getShGraphId()) || (this
				.getShGraphId() != null
				&& castOther.getShGraphId() != null && this.getShGraphId()
				.equals(castOther.getShGraphId())))
				&& ((this.getShFormId() == castOther.getShFormId()) || (this
						.getShFormId() != null
						&& castOther.getShFormId() != null && this
						.getShFormId().equals(castOther.getShFormId())))
				&& (this.getShTypeId() == castOther.getShTypeId())
				&& ((this.getShName() == castOther.getShName()) || (this
						.getShName() != null
						&& castOther.getShName() != null && this.getShName()
						.equals(castOther.getShName())))
				&& ((this.getShNumber() == castOther.getShNumber()) || (this
						.getShNumber() != null
						&& castOther.getShNumber() != null && this
						.getShNumber().equals(castOther.getShNumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getShGraphId() == null ? 0 : this.getShGraphId().hashCode());
		result = 37 * result
				+ (getShFormId() == null ? 0 : this.getShFormId().hashCode());
		result = 37 * result + this.getShTypeId();
		result = 37 * result
				+ (getShName() == null ? 0 : this.getShName().hashCode());
		result = 37 * result
				+ (getShNumber() == null ? 0 : this.getShNumber().hashCode());
		return result;
	}

}
