package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tblshapes generated by hbm2java
 */
public class Tblshapes implements java.io.Serializable {

	private TblshapesId id;

	public Tblshapes() {
	}

	public Tblshapes(TblshapesId id) {
		this.id = id;
	}

	public TblshapesId getId() {
		return this.id;
	}

	public void setId(TblshapesId id) {
		this.id = id;
	}

}
