package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * Tbltypeshapes generated by hbm2java
 */
public class Tbltypeshapes implements java.io.Serializable {

	private TbltypeshapesId id;

	public Tbltypeshapes() {
	}

	public Tbltypeshapes(TbltypeshapesId id) {
		this.id = id;
	}

	public TbltypeshapesId getId() {
		return this.id;
	}

	public void setId(TbltypeshapesId id) {
		this.id = id;
	}

}
