package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * TbltypeshapesId generated by hbm2java
 */
public class TbltypeshapesId implements java.io.Serializable {

	private Integer stId;
	private String stMaster;
	private String stDescription;

	public TbltypeshapesId() {
	}

	public TbltypeshapesId(String stMaster, String stDescription) {
		this.stMaster = stMaster;
		this.stDescription = stDescription;
	}

	public TbltypeshapesId(Integer stId, String stMaster, String stDescription) {
		this.stId = stId;
		this.stMaster = stMaster;
		this.stDescription = stDescription;
	}

	public Integer getStId() {
		return this.stId;
	}

	public void setStId(Integer stId) {
		this.stId = stId;
	}

	public String getStMaster() {
		return this.stMaster;
	}

	public void setStMaster(String stMaster) {
		this.stMaster = stMaster;
	}

	public String getStDescription() {
		return this.stDescription;
	}

	public void setStDescription(String stDescription) {
		this.stDescription = stDescription;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbltypeshapesId))
			return false;
		TbltypeshapesId castOther = (TbltypeshapesId) other;

		return ((this.getStId() == castOther.getStId()) || (this.getStId() != null
				&& castOther.getStId() != null && this.getStId().equals(
				castOther.getStId())))
				&& ((this.getStMaster() == castOther.getStMaster()) || (this
						.getStMaster() != null
						&& castOther.getStMaster() != null && this
						.getStMaster().equals(castOther.getStMaster())))
				&& ((this.getStDescription() == castOther.getStDescription()) || (this
						.getStDescription() != null
						&& castOther.getStDescription() != null && this
						.getStDescription()
						.equals(castOther.getStDescription())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getStId() == null ? 0 : this.getStId().hashCode());
		result = 37 * result
				+ (getStMaster() == null ? 0 : this.getStMaster().hashCode());
		result = 37
				* result
				+ (getStDescription() == null ? 0 : this.getStDescription()
						.hashCode());
		return result;
	}

}
