package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * ValoresGlobales generated by hbm2java
 */
public class ValoresGlobales implements java.io.Serializable {

	private ValoresGlobalesId id;

	public ValoresGlobales() {
	}

	public ValoresGlobales(ValoresGlobalesId id) {
		this.id = id;
	}

	public ValoresGlobalesId getId() {
		return this.id;
	}

	public void setId(ValoresGlobalesId id) {
		this.id = id;
	}

}
