package org.openossad.data.domain;

// Generated 03-oct-2010 22:27:17 by Hibernate Tools 3.2.4.GA

/**
 * ValoresGlobalesId generated by hbm2java
 */
public class ValoresGlobalesId implements java.io.Serializable {

	private int v1;
	private int v2;
	private int v3;
	private int v4;
	private Integer v5;
	private int v6;
	private int v7;
	private int v8;
	private int v9;
	private int v10;
	private int v11;
	private int v12;
	private int v13;
	private int v14;
	private int v15;
	private int v16;
	private int v17;
	private int v18;
	private int v19;

	public ValoresGlobalesId() {
	}

	public ValoresGlobalesId(int v1, int v2, int v3, int v4, int v6, int v7,
			int v8, int v9, int v10, int v11, int v12, int v13, int v14,
			int v15, int v16, int v17, int v18, int v19) {
		this.v1 = v1;
		this.v2 = v2;
		this.v3 = v3;
		this.v4 = v4;
		this.v6 = v6;
		this.v7 = v7;
		this.v8 = v8;
		this.v9 = v9;
		this.v10 = v10;
		this.v11 = v11;
		this.v12 = v12;
		this.v13 = v13;
		this.v14 = v14;
		this.v15 = v15;
		this.v16 = v16;
		this.v17 = v17;
		this.v18 = v18;
		this.v19 = v19;
	}

	public ValoresGlobalesId(int v1, int v2, int v3, int v4, Integer v5,
			int v6, int v7, int v8, int v9, int v10, int v11, int v12, int v13,
			int v14, int v15, int v16, int v17, int v18, int v19) {
		this.v1 = v1;
		this.v2 = v2;
		this.v3 = v3;
		this.v4 = v4;
		this.v5 = v5;
		this.v6 = v6;
		this.v7 = v7;
		this.v8 = v8;
		this.v9 = v9;
		this.v10 = v10;
		this.v11 = v11;
		this.v12 = v12;
		this.v13 = v13;
		this.v14 = v14;
		this.v15 = v15;
		this.v16 = v16;
		this.v17 = v17;
		this.v18 = v18;
		this.v19 = v19;
	}

	public int getV1() {
		return this.v1;
	}

	public void setV1(int v1) {
		this.v1 = v1;
	}

	public int getV2() {
		return this.v2;
	}

	public void setV2(int v2) {
		this.v2 = v2;
	}

	public int getV3() {
		return this.v3;
	}

	public void setV3(int v3) {
		this.v3 = v3;
	}

	public int getV4() {
		return this.v4;
	}

	public void setV4(int v4) {
		this.v4 = v4;
	}

	public Integer getV5() {
		return this.v5;
	}

	public void setV5(Integer v5) {
		this.v5 = v5;
	}

	public int getV6() {
		return this.v6;
	}

	public void setV6(int v6) {
		this.v6 = v6;
	}

	public int getV7() {
		return this.v7;
	}

	public void setV7(int v7) {
		this.v7 = v7;
	}

	public int getV8() {
		return this.v8;
	}

	public void setV8(int v8) {
		this.v8 = v8;
	}

	public int getV9() {
		return this.v9;
	}

	public void setV9(int v9) {
		this.v9 = v9;
	}

	public int getV10() {
		return this.v10;
	}

	public void setV10(int v10) {
		this.v10 = v10;
	}

	public int getV11() {
		return this.v11;
	}

	public void setV11(int v11) {
		this.v11 = v11;
	}

	public int getV12() {
		return this.v12;
	}

	public void setV12(int v12) {
		this.v12 = v12;
	}

	public int getV13() {
		return this.v13;
	}

	public void setV13(int v13) {
		this.v13 = v13;
	}

	public int getV14() {
		return this.v14;
	}

	public void setV14(int v14) {
		this.v14 = v14;
	}

	public int getV15() {
		return this.v15;
	}

	public void setV15(int v15) {
		this.v15 = v15;
	}

	public int getV16() {
		return this.v16;
	}

	public void setV16(int v16) {
		this.v16 = v16;
	}

	public int getV17() {
		return this.v17;
	}

	public void setV17(int v17) {
		this.v17 = v17;
	}

	public int getV18() {
		return this.v18;
	}

	public void setV18(int v18) {
		this.v18 = v18;
	}

	public int getV19() {
		return this.v19;
	}

	public void setV19(int v19) {
		this.v19 = v19;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ValoresGlobalesId))
			return false;
		ValoresGlobalesId castOther = (ValoresGlobalesId) other;

		return (this.getV1() == castOther.getV1())
				&& (this.getV2() == castOther.getV2())
				&& (this.getV3() == castOther.getV3())
				&& (this.getV4() == castOther.getV4())
				&& ((this.getV5() == castOther.getV5()) || (this.getV5() != null
						&& castOther.getV5() != null && this.getV5().equals(
						castOther.getV5())))
				&& (this.getV6() == castOther.getV6())
				&& (this.getV7() == castOther.getV7())
				&& (this.getV8() == castOther.getV8())
				&& (this.getV9() == castOther.getV9())
				&& (this.getV10() == castOther.getV10())
				&& (this.getV11() == castOther.getV11())
				&& (this.getV12() == castOther.getV12())
				&& (this.getV13() == castOther.getV13())
				&& (this.getV14() == castOther.getV14())
				&& (this.getV15() == castOther.getV15())
				&& (this.getV16() == castOther.getV16())
				&& (this.getV17() == castOther.getV17())
				&& (this.getV18() == castOther.getV18())
				&& (this.getV19() == castOther.getV19());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getV1();
		result = 37 * result + this.getV2();
		result = 37 * result + this.getV3();
		result = 37 * result + this.getV4();
		result = 37 * result + (getV5() == null ? 0 : this.getV5().hashCode());
		result = 37 * result + this.getV6();
		result = 37 * result + this.getV7();
		result = 37 * result + this.getV8();
		result = 37 * result + this.getV9();
		result = 37 * result + this.getV10();
		result = 37 * result + this.getV11();
		result = 37 * result + this.getV12();
		result = 37 * result + this.getV13();
		result = 37 * result + this.getV14();
		result = 37 * result + this.getV15();
		result = 37 * result + this.getV16();
		result = 37 * result + this.getV17();
		result = 37 * result + this.getV18();
		result = 37 * result + this.getV19();
		return result;
	}

}
